// 挂载点信息
syntax = "proto3";
package caster.context;

// 所有挂载点上线之后都会在挂载点列表中留下记录，区别于实时状态表

message MptInfo {
  string uid = 1; //挂载点名称

  uint64 create_time = 2; // 创建日期,初次记录日期
  uint64 update_time = 3; // 最后更新日期

  string login_user = 4; // 登录使用的用户名
  string login_ip   = 5; // 登录IP
  string login_port = 6; // 登录端口

    // 挂载点规则
  int32 opt_hedden  = 7; // 隐藏挂载点（非公开挂载点）
  int32 opt_disable = 8; // 禁止播发数据
  int32 opt_decode  = 9; // 解析原始数据流

  int32 opt_group_type = 10; // 分组类型   公共（所有用户可见）   分组（仅分组内可见）

}