// 账号状态信息
syntax = "proto3";
package caster.context;

enum ActType{
  ACT_TYPE_UNKNOWN = 0;
  ACT_TYPE_COMMON  = 1;
  ACT_TYPE_NEAREST = 2;
  ACT_TYPE_PULL    = 3;
  ACT_TYPE_TCPC    = 4;
  ACT_TYPE_TCPS    = 5;
  ACT_TYPE_PROXY   = 6;
  ACT_TYPE_ALIAS   = 7;
}

enum ActStateType{
  ACT_STAT_TYPE_UNKNOWN = 0;
  ACT_STAT_TYPE_ENABLE  = 1;
  ACT_STAT_TYPE_DISABLE = 2;
}

message ActStat {
  string uid = 1; //UID

    // 账号状态  // 启用/停用

    // 激活时间  // 

    // 过期时间  // 

    // 注册时间  //

    // 在线状态信息
        // 基站接入UID
        // 移动站接入UID

    //

}


// 