// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/ClientState.proto
// Protobuf C++ Version: 7.35.0-dev

#include "core/ClientState.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::caster::core::ClientState
        {&::_pbi::kDescriptorMethods, &::descriptor_table_core_2fClientState_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace caster {
namespace core {

inline constexpr ClientState::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        uid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        source_group_uid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        create_time_{::uint64_t{0u}},
        update_time_{::uint64_t{0u}},
        ecef_x_{0},
        ecef_y_{0},
        ecef_z_{0},
        quality_{0},
        sat_num_{0},
        diff_{0},
        distance_{0},
        position_update_time_{0} {}

template <typename>
constexpr ClientState::ClientState(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ClientState_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct ClientStateGlobalsTypeInternal {
  constexpr ClientStateGlobalsTypeInternal() : _default(::_pbi::ConstantInitialized{}) {}
  ~ClientStateGlobalsTypeInternal() {}
  union {
    ClientState _default;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClientStateGlobalsTypeInternal _ClientState_globals_;
}  // namespace core
}  // namespace caster
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_core_2fClientState_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_core_2fClientState_2eproto = nullptr;
const ::uint32_t
    TableStruct_core_2fClientState_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::caster::core::ClientState, _impl_._has_bits_),
        15, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::caster::core::ClientState, _impl_.uid_),
        PROTOBUF_FIELD_OFFSET(::caster::core::ClientState, _impl_.create_time_),
        PROTOBUF_FIELD_OFFSET(::caster::core::ClientState, _impl_.update_time_),
        PROTOBUF_FIELD_OFFSET(::caster::core::ClientState, _impl_.source_group_uid_),
        PROTOBUF_FIELD_OFFSET(::caster::core::ClientState, _impl_.ecef_x_),
        PROTOBUF_FIELD_OFFSET(::caster::core::ClientState, _impl_.ecef_y_),
        PROTOBUF_FIELD_OFFSET(::caster::core::ClientState, _impl_.ecef_z_),
        PROTOBUF_FIELD_OFFSET(::caster::core::ClientState, _impl_.quality_),
        PROTOBUF_FIELD_OFFSET(::caster::core::ClientState, _impl_.sat_num_),
        PROTOBUF_FIELD_OFFSET(::caster::core::ClientState, _impl_.diff_),
        PROTOBUF_FIELD_OFFSET(::caster::core::ClientState, _impl_.distance_),
        PROTOBUF_FIELD_OFFSET(::caster::core::ClientState, _impl_.position_update_time_),
        0,
        2,
        3,
        1,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::caster::core::ClientState)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::caster::core::_ClientState_globals_._default,
};
const char descriptor_table_protodef_core_2fClientState_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\026core/ClientState.proto\022\013caster.core\"\356\001"
    "\n\013ClientState\022\013\n\003uid\030\001 \001(\t\022\023\n\013create_tim"
    "e\030\002 \001(\004\022\023\n\013update_time\030\003 \001(\004\022\030\n\020source_g"
    "roup_uid\030\004 \001(\t\022\016\n\006ecef_x\030\005 \001(\001\022\016\n\006ecef_y"
    "\030\006 \001(\001\022\016\n\006ecef_z\030\007 \001(\001\022\017\n\007quality\030\010 \001(\005\022"
    "\017\n\007sat_num\030\t \001(\005\022\014\n\004diff\030\n \001(\001\022\020\n\010distan"
    "ce\030\013 \001(\001\022\034\n\024position_update_time\030\014 \001(\001b\006"
    "proto3"
};
static ::absl::once_flag descriptor_table_core_2fClientState_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_core_2fClientState_2eproto = {
    false,
    false,
    286,
    descriptor_table_protodef_core_2fClientState_2eproto,
    "core/ClientState.proto",
    &descriptor_table_core_2fClientState_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_core_2fClientState_2eproto::offsets,
    file_level_enum_descriptors_core_2fClientState_2eproto,
    file_level_service_descriptors_core_2fClientState_2eproto,
};
namespace caster {
namespace core {
// ===================================================================

class ClientState::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ClientState>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ClientState, _impl_._has_bits_);
};

ClientState::ClientState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ClientState_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:caster.core.ClientState)
}
PROTOBUF_NDEBUG_INLINE ClientState::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::caster::core::ClientState& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        uid_(arena, from.uid_),
        source_group_uid_(arena, from.source_group_uid_) {}

ClientState::ClientState(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ClientState& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ClientState_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ClientState* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, create_time_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, create_time_),
           offsetof(Impl_, position_update_time_) -
               offsetof(Impl_, create_time_) +
               sizeof(Impl_::position_update_time_));

  // @@protoc_insertion_point(copy_constructor:caster.core.ClientState)
}
PROTOBUF_NDEBUG_INLINE ClientState::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        uid_(arena),
        source_group_uid_(arena) {}

inline void ClientState::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, create_time_),
           0,
           offsetof(Impl_, position_update_time_) -
               offsetof(Impl_, create_time_) +
               sizeof(Impl_::position_update_time_));
}
ClientState::~ClientState() {
  // @@protoc_insertion_point(destructor:caster.core.ClientState)
  SharedDtor(*this);
}
inline void ClientState::SharedDtor(MessageLite& self) {
  ClientState& this_ = static_cast<ClientState&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.uid_.Destroy();
  this_._impl_.source_group_uid_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ClientState::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ClientState(arena);
}
constexpr auto ClientState::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ClientState),
                                            alignof(ClientState));
}
constexpr auto ClientState::InternalGenerateClassData_() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ClientState_globals_._default,
          &_table_.header,
          nullptr,  // IsInitialized
          &ClientState::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ClientState>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ClientState::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ClientState>(), &ClientState::ByteSizeLong,
              &ClientState::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ClientState, _impl_._cached_size_),
          false,
      },
      &file_reflection_data[0]};
#else  // !PROTOBUF_MESSAGE_GLOBALS
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ClientState_globals_._default,
          &_table_.header,
          nullptr,  // IsInitialized
          &ClientState::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ClientState>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ClientState::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ClientState>(), &ClientState::ByteSizeLong,
              &ClientState::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ClientState, _impl_._cached_size_),
          false,
      },
      &::_pbi::kDescriptorMethods,
      &descriptor_table_core_2fClientState_2eproto,
      nullptr,  // tracker
  };
#endif  // PROTOBUF_MESSAGE_GLOBALS
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ClientState_class_data_ =
        ClientState::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ClientState::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ClientState_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ClientState_class_data_.tc_table);
  return ClientState_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 12, 0, 59, 2>
ClientState::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ClientState, _impl_._has_bits_),
    0, // no _extensions_
    12, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294963200,  // skipmap
    offsetof(decltype(_table_), field_entries),
    12,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ClientState_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::caster::core::ClientState>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string uid = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(ClientState, _impl_.uid_)}},
    // uint64 create_time = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ClientState, _impl_.create_time_), 2>(),
     {16, 2, 0,
      PROTOBUF_FIELD_OFFSET(ClientState, _impl_.create_time_)}},
    // uint64 update_time = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ClientState, _impl_.update_time_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(ClientState, _impl_.update_time_)}},
    // string source_group_uid = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 1, 0,
      PROTOBUF_FIELD_OFFSET(ClientState, _impl_.source_group_uid_)}},
    // double ecef_x = 5;
    {::_pbi::TcParser::FastF64S1,
     {41, 4, 0,
      PROTOBUF_FIELD_OFFSET(ClientState, _impl_.ecef_x_)}},
    // double ecef_y = 6;
    {::_pbi::TcParser::FastF64S1,
     {49, 5, 0,
      PROTOBUF_FIELD_OFFSET(ClientState, _impl_.ecef_y_)}},
    // double ecef_z = 7;
    {::_pbi::TcParser::FastF64S1,
     {57, 6, 0,
      PROTOBUF_FIELD_OFFSET(ClientState, _impl_.ecef_z_)}},
    // int32 quality = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ClientState, _impl_.quality_), 7>(),
     {64, 7, 0,
      PROTOBUF_FIELD_OFFSET(ClientState, _impl_.quality_)}},
    // int32 sat_num = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ClientState, _impl_.sat_num_), 8>(),
     {72, 8, 0,
      PROTOBUF_FIELD_OFFSET(ClientState, _impl_.sat_num_)}},
    // double diff = 10;
    {::_pbi::TcParser::FastF64S1,
     {81, 9, 0,
      PROTOBUF_FIELD_OFFSET(ClientState, _impl_.diff_)}},
    // double distance = 11;
    {::_pbi::TcParser::FastF64S1,
     {89, 10, 0,
      PROTOBUF_FIELD_OFFSET(ClientState, _impl_.distance_)}},
    // double position_update_time = 12;
    {::_pbi::TcParser::FastF64S1,
     {97, 11, 0,
      PROTOBUF_FIELD_OFFSET(ClientState, _impl_.position_update_time_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string uid = 1;
    {PROTOBUF_FIELD_OFFSET(ClientState, _impl_.uid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint64 create_time = 2;
    {PROTOBUF_FIELD_OFFSET(ClientState, _impl_.create_time_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 update_time = 3;
    {PROTOBUF_FIELD_OFFSET(ClientState, _impl_.update_time_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // string source_group_uid = 4;
    {PROTOBUF_FIELD_OFFSET(ClientState, _impl_.source_group_uid_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double ecef_x = 5;
    {PROTOBUF_FIELD_OFFSET(ClientState, _impl_.ecef_x_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double ecef_y = 6;
    {PROTOBUF_FIELD_OFFSET(ClientState, _impl_.ecef_y_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double ecef_z = 7;
    {PROTOBUF_FIELD_OFFSET(ClientState, _impl_.ecef_z_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // int32 quality = 8;
    {PROTOBUF_FIELD_OFFSET(ClientState, _impl_.quality_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 sat_num = 9;
    {PROTOBUF_FIELD_OFFSET(ClientState, _impl_.sat_num_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // double diff = 10;
    {PROTOBUF_FIELD_OFFSET(ClientState, _impl_.diff_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double distance = 11;
    {PROTOBUF_FIELD_OFFSET(ClientState, _impl_.distance_), _Internal::kHasBitsOffset + 10, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double position_update_time = 12;
    {PROTOBUF_FIELD_OFFSET(ClientState, _impl_.position_update_time_), _Internal::kHasBitsOffset + 11, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
    "\27\3\0\0\20\0\0\0\0\0\0\0\0\0\0\0"
    "caster.core.ClientState"
    "uid"
    "source_group_uid"
  }},
};
PROTOBUF_NOINLINE void ClientState::Clear() {
// @@protoc_insertion_point(message_clear_start:caster.core.ClientState)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.uid_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.source_group_uid_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000fcU)) {
    ::memset(&_impl_.create_time_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.quality_) -
        reinterpret_cast<char*>(&_impl_.create_time_)) + sizeof(_impl_.quality_));
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000f00U)) {
    ::memset(&_impl_.sat_num_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.position_update_time_) -
        reinterpret_cast<char*>(&_impl_.sat_num_)) + sizeof(_impl_.position_update_time_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ClientState::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ClientState& this_ = static_cast<const ClientState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ClientState::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ClientState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:caster.core.ClientState)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string uid = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_uid().empty()) {
      const ::std::string& _s = this_._internal_uid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "caster.core.ClientState.uid");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // uint64 create_time = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_create_time() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          2, this_._internal_create_time(), target);
    }
  }

  // uint64 update_time = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_update_time() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          3, this_._internal_update_time(), target);
    }
  }

  // string source_group_uid = 4;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_source_group_uid().empty()) {
      const ::std::string& _s = this_._internal_source_group_uid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "caster.core.ClientState.source_group_uid");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // double ecef_x = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_ecef_x()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          5, this_._internal_ecef_x(), target);
    }
  }

  // double ecef_y = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_ecef_y()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          6, this_._internal_ecef_y(), target);
    }
  }

  // double ecef_z = 7;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_ecef_z()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          7, this_._internal_ecef_z(), target);
    }
  }

  // int32 quality = 8;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_quality() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<8>(
              stream, this_._internal_quality(), target);
    }
  }

  // int32 sat_num = 9;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (this_._internal_sat_num() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<9>(
              stream, this_._internal_sat_num(), target);
    }
  }

  // double diff = 10;
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_diff()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          10, this_._internal_diff(), target);
    }
  }

  // double distance = 11;
  if (CheckHasBit(cached_has_bits, 0x00000400U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_distance()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          11, this_._internal_distance(), target);
    }
  }

  // double position_update_time = 12;
  if (CheckHasBit(cached_has_bits, 0x00000800U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_position_update_time()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          12, this_._internal_position_update_time(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:caster.core.ClientState)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ClientState::ByteSizeLong(const MessageLite& base) {
  const ClientState& this_ = static_cast<const ClientState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ClientState::ByteSizeLong() const {
  const ClientState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:caster.core.ClientState)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // string uid = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_uid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_uid());
      }
    }
    // string source_group_uid = 4;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_source_group_uid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_source_group_uid());
      }
    }
    // uint64 create_time = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_create_time() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_create_time());
      }
    }
    // uint64 update_time = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_update_time() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_update_time());
      }
    }
    // double ecef_x = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_ecef_x()) != 0) {
        total_size += 9;
      }
    }
    // double ecef_y = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_ecef_y()) != 0) {
        total_size += 9;
      }
    }
    // double ecef_z = 7;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_ecef_z()) != 0) {
        total_size += 9;
      }
    }
    // int32 quality = 8;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_quality() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_quality());
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000f00U)) {
    // int32 sat_num = 9;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (this_._internal_sat_num() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_sat_num());
      }
    }
    // double diff = 10;
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_diff()) != 0) {
        total_size += 9;
      }
    }
    // double distance = 11;
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_distance()) != 0) {
        total_size += 9;
      }
    }
    // double position_update_time = 12;
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_position_update_time()) != 0) {
        total_size += 9;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ClientState::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ClientState*>(&to_msg);
  auto& from = static_cast<const ClientState&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:caster.core.ClientState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_uid().empty()) {
        _this->_internal_set_uid(from._internal_uid());
      } else {
        if (_this->_impl_.uid_.IsDefault()) {
          _this->_internal_set_uid("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_source_group_uid().empty()) {
        _this->_internal_set_source_group_uid(from._internal_source_group_uid());
      } else {
        if (_this->_impl_.source_group_uid_.IsDefault()) {
          _this->_internal_set_source_group_uid("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_create_time() != 0) {
        _this->_impl_.create_time_ = from._impl_.create_time_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_update_time() != 0) {
        _this->_impl_.update_time_ = from._impl_.update_time_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_ecef_x()) != 0) {
        _this->_impl_.ecef_x_ = from._impl_.ecef_x_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_ecef_y()) != 0) {
        _this->_impl_.ecef_y_ = from._impl_.ecef_y_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_ecef_z()) != 0) {
        _this->_impl_.ecef_z_ = from._impl_.ecef_z_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_quality() != 0) {
        _this->_impl_.quality_ = from._impl_.quality_;
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000f00U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (from._internal_sat_num() != 0) {
        _this->_impl_.sat_num_ = from._impl_.sat_num_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_diff()) != 0) {
        _this->_impl_.diff_ = from._impl_.diff_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_distance()) != 0) {
        _this->_impl_.distance_ = from._impl_.distance_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_position_update_time()) != 0) {
        _this->_impl_.position_update_time_ = from._impl_.position_update_time_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ClientState::CopyFrom(const ClientState& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:caster.core.ClientState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ClientState::InternalSwap(ClientState* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uid_, &other->_impl_.uid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.source_group_uid_, &other->_impl_.source_group_uid_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ClientState, _impl_.position_update_time_)
      + sizeof(ClientState::_impl_.position_update_time_)
      - PROTOBUF_FIELD_OFFSET(ClientState, _impl_.create_time_)>(
          reinterpret_cast<char*>(&_impl_.create_time_),
          reinterpret_cast<char*>(&other->_impl_.create_time_));
}

::google::protobuf::Metadata ClientState::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace core
}  // namespace caster
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_core_2fClientState_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
