// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/ClientState.proto
// Protobuf C++ Version: 7.35.0-dev

#ifndef core_2fClientState_2eproto_2epb_2eh
#define core_2fClientState_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_core_2fClientState_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_core_2fClientState_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_core_2fClientState_2eproto;
}  // extern "C"
namespace caster {
namespace core {
class ClientState;
struct ClientStateGlobalsTypeInternal;
extern ClientStateGlobalsTypeInternal _ClientState_globals_;
extern const ::google::protobuf::internal::ClassDataFull ClientState_class_data_;
}  // namespace core
}  // namespace caster
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace caster {
namespace core {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED ClientState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:caster.core.ClientState) */ {
 public:
  inline ClientState() : ClientState(nullptr) {}
  ~ClientState() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ClientState* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ClientState));
  }
#endif

  template <typename = void>
  explicit constexpr ClientState(::google::protobuf::internal::ConstantInitialized);

  inline ClientState(const ClientState& from) : ClientState(nullptr, from) {}
  inline ClientState(ClientState&& from) noexcept
      : ClientState(nullptr, ::std::move(from)) {}
  inline ClientState& operator=(const ClientState& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientState& operator=(ClientState&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const ClientState& default_instance() {
    return *reinterpret_cast<const ClientState*>(&_ClientState_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ClientState& a, ClientState& b) { a.Swap(&b); }
  inline void Swap(ClientState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] ClientState* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ClientState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ClientState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ClientState& from) { ClientState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ClientState* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "caster.core.ClientState"; }

  explicit ClientState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ClientState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ClientState& from);
  ClientState(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ClientState&& from) noexcept
      : ClientState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUidFieldNumber = 1,
    kLoginMptFieldNumber = 4,
    kAliasMptFieldNumber = 5,
    kAccountFieldNumber = 7,
    kIpFieldNumber = 8,
    kOnlineTimeFieldNumber = 2,
    kUpdateTimeFieldNumber = 3,
    kTypeFieldNumber = 6,
    kPortFieldNumber = 9,
    kOnlineSecondsFieldNumber = 10,
    kTcpDelayFieldNumber = 11,
    kEcefXFieldNumber = 12,
    kEcefYFieldNumber = 13,
    kEcefZFieldNumber = 14,
    kPositionUpdateTimeFieldNumber = 15,
    kQualityFieldNumber = 16,
    kSatNumFieldNumber = 17,
    kDiffFieldNumber = 18,
    kDistanceFieldNumber = 19,
  };
  // string uid = 1;
  void clear_uid() ;
  [[nodiscard]] const ::std::string& uid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_uid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_uid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_uid();
  void set_allocated_uid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_uid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_uid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_uid();

  public:
  // string login_mpt = 4;
  void clear_login_mpt() ;
  [[nodiscard]] const ::std::string& login_mpt() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_login_mpt(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_login_mpt();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_login_mpt();
  void set_allocated_login_mpt(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_login_mpt() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_login_mpt(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_login_mpt();

  public:
  // string alias_mpt = 5;
  void clear_alias_mpt() ;
  [[nodiscard]] const ::std::string& alias_mpt() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_alias_mpt(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_alias_mpt();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_alias_mpt();
  void set_allocated_alias_mpt(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_alias_mpt() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_alias_mpt(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_alias_mpt();

  public:
  // string account = 7;
  void clear_account() ;
  [[nodiscard]] const ::std::string& account() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_account(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_account();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_account();
  void set_allocated_account(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_account() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_account(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_account();

  public:
  // string ip = 8;
  void clear_ip() ;
  [[nodiscard]] const ::std::string& ip() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_ip(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_ip();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_ip();
  void set_allocated_ip(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_ip() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_ip(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_ip();

  public:
  // uint64 online_time = 2;
  void clear_online_time() ;
  [[nodiscard]] ::uint64_t online_time() const;
  void set_online_time(::uint64_t value);

  private:
  ::uint64_t _internal_online_time() const;
  void _internal_set_online_time(::uint64_t value);

  public:
  // uint64 update_time = 3;
  void clear_update_time() ;
  [[nodiscard]] ::uint64_t update_time() const;
  void set_update_time(::uint64_t value);

  private:
  ::uint64_t _internal_update_time() const;
  void _internal_set_update_time(::uint64_t value);

  public:
  // int32 type = 6;
  void clear_type() ;
  [[nodiscard]] ::int32_t type() const;
  void set_type(::int32_t value);

  private:
  ::int32_t _internal_type() const;
  void _internal_set_type(::int32_t value);

  public:
  // int32 port = 9;
  void clear_port() ;
  [[nodiscard]] ::int32_t port() const;
  void set_port(::int32_t value);

  private:
  ::int32_t _internal_port() const;
  void _internal_set_port(::int32_t value);

  public:
  // uint64 online_seconds = 10;
  void clear_online_seconds() ;
  [[nodiscard]] ::uint64_t online_seconds() const;
  void set_online_seconds(::uint64_t value);

  private:
  ::uint64_t _internal_online_seconds() const;
  void _internal_set_online_seconds(::uint64_t value);

  public:
  // uint64 tcp_delay = 11;
  void clear_tcp_delay() ;
  [[nodiscard]] ::uint64_t tcp_delay() const;
  void set_tcp_delay(::uint64_t value);

  private:
  ::uint64_t _internal_tcp_delay() const;
  void _internal_set_tcp_delay(::uint64_t value);

  public:
  // double ecef_x = 12;
  void clear_ecef_x() ;
  [[nodiscard]] double ecef_x() const;
  void set_ecef_x(double value);

  private:
  double _internal_ecef_x() const;
  void _internal_set_ecef_x(double value);

  public:
  // double ecef_y = 13;
  void clear_ecef_y() ;
  [[nodiscard]] double ecef_y() const;
  void set_ecef_y(double value);

  private:
  double _internal_ecef_y() const;
  void _internal_set_ecef_y(double value);

  public:
  // double ecef_z = 14;
  void clear_ecef_z() ;
  [[nodiscard]] double ecef_z() const;
  void set_ecef_z(double value);

  private:
  double _internal_ecef_z() const;
  void _internal_set_ecef_z(double value);

  public:
  // int64 position_update_time = 15;
  void clear_position_update_time() ;
  [[nodiscard]] ::int64_t position_update_time() const;
  void set_position_update_time(::int64_t value);

  private:
  ::int64_t _internal_position_update_time() const;
  void _internal_set_position_update_time(::int64_t value);

  public:
  // int32 quality = 16;
  void clear_quality() ;
  [[nodiscard]] ::int32_t quality() const;
  void set_quality(::int32_t value);

  private:
  ::int32_t _internal_quality() const;
  void _internal_set_quality(::int32_t value);

  public:
  // int32 sat_num = 17;
  void clear_sat_num() ;
  [[nodiscard]] ::int32_t sat_num() const;
  void set_sat_num(::int32_t value);

  private:
  ::int32_t _internal_sat_num() const;
  void _internal_set_sat_num(::int32_t value);

  public:
  // double diff = 18;
  void clear_diff() ;
  [[nodiscard]] double diff() const;
  void set_diff(double value);

  private:
  double _internal_diff() const;
  void _internal_set_diff(double value);

  public:
  // double distance = 19;
  void clear_distance() ;
  [[nodiscard]] double distance() const;
  void set_distance(double value);

  private:
  double _internal_distance() const;
  void _internal_set_distance(double value);

  public:
  // @@protoc_insertion_point(class_scope:caster.core.ClientState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<5, 19,
                                   0, 78,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ClientState& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr uid_;
    ::google::protobuf::internal::ArenaStringPtr login_mpt_;
    ::google::protobuf::internal::ArenaStringPtr alias_mpt_;
    ::google::protobuf::internal::ArenaStringPtr account_;
    ::google::protobuf::internal::ArenaStringPtr ip_;
    ::uint64_t online_time_;
    ::uint64_t update_time_;
    ::int32_t type_;
    ::int32_t port_;
    ::uint64_t online_seconds_;
    ::uint64_t tcp_delay_;
    double ecef_x_;
    double ecef_y_;
    double ecef_z_;
    ::int64_t position_update_time_;
    ::int32_t quality_;
    ::int32_t sat_num_;
    double diff_;
    double distance_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_core_2fClientState_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ClientState_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ClientState

// string uid = 1;
inline void ClientState::clear_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& ClientState::uid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.uid)
  return _internal_uid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ClientState::set_uid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.uid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ClientState.uid)
}
inline ::std::string* PROTOBUF_NONNULL ClientState::mutable_uid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_uid();
  // @@protoc_insertion_point(field_mutable:caster.core.ClientState.uid)
  return _s;
}
inline const ::std::string& ClientState::_internal_uid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uid_.Get();
}
inline void ClientState::_internal_set_uid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ClientState::_internal_mutable_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.uid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ClientState::release_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ClientState.uid)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.uid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.uid_.Set("", GetArena());
  }
  return released;
}
inline void ClientState::set_allocated_uid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.uid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.uid_.IsDefault()) {
    _impl_.uid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ClientState.uid)
}

// uint64 online_time = 2;
inline void ClientState::clear_online_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.online_time_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::uint64_t ClientState::online_time() const {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.online_time)
  return _internal_online_time();
}
inline void ClientState::set_online_time(::uint64_t value) {
  _internal_set_online_time(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:caster.core.ClientState.online_time)
}
inline ::uint64_t ClientState::_internal_online_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.online_time_;
}
inline void ClientState::_internal_set_online_time(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.online_time_ = value;
}

// uint64 update_time = 3;
inline void ClientState::clear_update_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.update_time_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::uint64_t ClientState::update_time() const {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.update_time)
  return _internal_update_time();
}
inline void ClientState::set_update_time(::uint64_t value) {
  _internal_set_update_time(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:caster.core.ClientState.update_time)
}
inline ::uint64_t ClientState::_internal_update_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.update_time_;
}
inline void ClientState::_internal_set_update_time(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.update_time_ = value;
}

// string login_mpt = 4;
inline void ClientState::clear_login_mpt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.login_mpt_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& ClientState::login_mpt() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.login_mpt)
  return _internal_login_mpt();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ClientState::set_login_mpt(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.login_mpt_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ClientState.login_mpt)
}
inline ::std::string* PROTOBUF_NONNULL ClientState::mutable_login_mpt()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_login_mpt();
  // @@protoc_insertion_point(field_mutable:caster.core.ClientState.login_mpt)
  return _s;
}
inline const ::std::string& ClientState::_internal_login_mpt() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.login_mpt_.Get();
}
inline void ClientState::_internal_set_login_mpt(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.login_mpt_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ClientState::_internal_mutable_login_mpt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.login_mpt_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ClientState::release_login_mpt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ClientState.login_mpt)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.login_mpt_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.login_mpt_.Set("", GetArena());
  }
  return released;
}
inline void ClientState::set_allocated_login_mpt(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.login_mpt_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.login_mpt_.IsDefault()) {
    _impl_.login_mpt_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ClientState.login_mpt)
}

// string alias_mpt = 5;
inline void ClientState::clear_alias_mpt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.alias_mpt_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& ClientState::alias_mpt() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.alias_mpt)
  return _internal_alias_mpt();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ClientState::set_alias_mpt(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.alias_mpt_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ClientState.alias_mpt)
}
inline ::std::string* PROTOBUF_NONNULL ClientState::mutable_alias_mpt()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_alias_mpt();
  // @@protoc_insertion_point(field_mutable:caster.core.ClientState.alias_mpt)
  return _s;
}
inline const ::std::string& ClientState::_internal_alias_mpt() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.alias_mpt_.Get();
}
inline void ClientState::_internal_set_alias_mpt(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.alias_mpt_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ClientState::_internal_mutable_alias_mpt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.alias_mpt_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ClientState::release_alias_mpt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ClientState.alias_mpt)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.alias_mpt_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.alias_mpt_.Set("", GetArena());
  }
  return released;
}
inline void ClientState::set_allocated_alias_mpt(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.alias_mpt_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.alias_mpt_.IsDefault()) {
    _impl_.alias_mpt_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ClientState.alias_mpt)
}

// int32 type = 6;
inline void ClientState::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::int32_t ClientState::type() const {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.type)
  return _internal_type();
}
inline void ClientState::set_type(::int32_t value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:caster.core.ClientState.type)
}
inline ::int32_t ClientState::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.type_;
}
inline void ClientState::_internal_set_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// string account = 7;
inline void ClientState::clear_account() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.account_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& ClientState::account() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.account)
  return _internal_account();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ClientState::set_account(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.account_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ClientState.account)
}
inline ::std::string* PROTOBUF_NONNULL ClientState::mutable_account()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_account();
  // @@protoc_insertion_point(field_mutable:caster.core.ClientState.account)
  return _s;
}
inline const ::std::string& ClientState::_internal_account() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.account_.Get();
}
inline void ClientState::_internal_set_account(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.account_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ClientState::_internal_mutable_account() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.account_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ClientState::release_account() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ClientState.account)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.account_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.account_.Set("", GetArena());
  }
  return released;
}
inline void ClientState::set_allocated_account(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.account_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.account_.IsDefault()) {
    _impl_.account_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ClientState.account)
}

// string ip = 8;
inline void ClientState::clear_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::std::string& ClientState::ip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.ip)
  return _internal_ip();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ClientState::set_ip(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.ip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ClientState.ip)
}
inline ::std::string* PROTOBUF_NONNULL ClientState::mutable_ip()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:caster.core.ClientState.ip)
  return _s;
}
inline const ::std::string& ClientState::_internal_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ip_.Get();
}
inline void ClientState::_internal_set_ip(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ClientState::_internal_mutable_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ip_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ClientState::release_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ClientState.ip)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000010U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  auto* released = _impl_.ip_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.ip_.Set("", GetArena());
  }
  return released;
}
inline void ClientState::set_allocated_ip(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  _impl_.ip_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ip_.IsDefault()) {
    _impl_.ip_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ClientState.ip)
}

// int32 port = 9;
inline void ClientState::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline ::int32_t ClientState::port() const {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.port)
  return _internal_port();
}
inline void ClientState::set_port(::int32_t value) {
  _internal_set_port(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:caster.core.ClientState.port)
}
inline ::int32_t ClientState::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_;
}
inline void ClientState::_internal_set_port(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = value;
}

// uint64 online_seconds = 10;
inline void ClientState::clear_online_seconds() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.online_seconds_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000200U);
}
inline ::uint64_t ClientState::online_seconds() const {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.online_seconds)
  return _internal_online_seconds();
}
inline void ClientState::set_online_seconds(::uint64_t value) {
  _internal_set_online_seconds(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_set:caster.core.ClientState.online_seconds)
}
inline ::uint64_t ClientState::_internal_online_seconds() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.online_seconds_;
}
inline void ClientState::_internal_set_online_seconds(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.online_seconds_ = value;
}

// uint64 tcp_delay = 11;
inline void ClientState::clear_tcp_delay() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tcp_delay_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000400U);
}
inline ::uint64_t ClientState::tcp_delay() const {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.tcp_delay)
  return _internal_tcp_delay();
}
inline void ClientState::set_tcp_delay(::uint64_t value) {
  _internal_set_tcp_delay(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000400U);
  // @@protoc_insertion_point(field_set:caster.core.ClientState.tcp_delay)
}
inline ::uint64_t ClientState::_internal_tcp_delay() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tcp_delay_;
}
inline void ClientState::_internal_set_tcp_delay(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tcp_delay_ = value;
}

// double ecef_x = 12;
inline void ClientState::clear_ecef_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ecef_x_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000800U);
}
inline double ClientState::ecef_x() const {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.ecef_x)
  return _internal_ecef_x();
}
inline void ClientState::set_ecef_x(double value) {
  _internal_set_ecef_x(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000800U);
  // @@protoc_insertion_point(field_set:caster.core.ClientState.ecef_x)
}
inline double ClientState::_internal_ecef_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ecef_x_;
}
inline void ClientState::_internal_set_ecef_x(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ecef_x_ = value;
}

// double ecef_y = 13;
inline void ClientState::clear_ecef_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ecef_y_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00001000U);
}
inline double ClientState::ecef_y() const {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.ecef_y)
  return _internal_ecef_y();
}
inline void ClientState::set_ecef_y(double value) {
  _internal_set_ecef_y(value);
  SetHasBit(_impl_._has_bits_[0], 0x00001000U);
  // @@protoc_insertion_point(field_set:caster.core.ClientState.ecef_y)
}
inline double ClientState::_internal_ecef_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ecef_y_;
}
inline void ClientState::_internal_set_ecef_y(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ecef_y_ = value;
}

// double ecef_z = 14;
inline void ClientState::clear_ecef_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ecef_z_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00002000U);
}
inline double ClientState::ecef_z() const {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.ecef_z)
  return _internal_ecef_z();
}
inline void ClientState::set_ecef_z(double value) {
  _internal_set_ecef_z(value);
  SetHasBit(_impl_._has_bits_[0], 0x00002000U);
  // @@protoc_insertion_point(field_set:caster.core.ClientState.ecef_z)
}
inline double ClientState::_internal_ecef_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ecef_z_;
}
inline void ClientState::_internal_set_ecef_z(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ecef_z_ = value;
}

// int64 position_update_time = 15;
inline void ClientState::clear_position_update_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_update_time_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00004000U);
}
inline ::int64_t ClientState::position_update_time() const {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.position_update_time)
  return _internal_position_update_time();
}
inline void ClientState::set_position_update_time(::int64_t value) {
  _internal_set_position_update_time(value);
  SetHasBit(_impl_._has_bits_[0], 0x00004000U);
  // @@protoc_insertion_point(field_set:caster.core.ClientState.position_update_time)
}
inline ::int64_t ClientState::_internal_position_update_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.position_update_time_;
}
inline void ClientState::_internal_set_position_update_time(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_update_time_ = value;
}

// int32 quality = 16;
inline void ClientState::clear_quality() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.quality_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00008000U);
}
inline ::int32_t ClientState::quality() const {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.quality)
  return _internal_quality();
}
inline void ClientState::set_quality(::int32_t value) {
  _internal_set_quality(value);
  SetHasBit(_impl_._has_bits_[0], 0x00008000U);
  // @@protoc_insertion_point(field_set:caster.core.ClientState.quality)
}
inline ::int32_t ClientState::_internal_quality() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.quality_;
}
inline void ClientState::_internal_set_quality(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.quality_ = value;
}

// int32 sat_num = 17;
inline void ClientState::clear_sat_num() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sat_num_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00010000U);
}
inline ::int32_t ClientState::sat_num() const {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.sat_num)
  return _internal_sat_num();
}
inline void ClientState::set_sat_num(::int32_t value) {
  _internal_set_sat_num(value);
  SetHasBit(_impl_._has_bits_[0], 0x00010000U);
  // @@protoc_insertion_point(field_set:caster.core.ClientState.sat_num)
}
inline ::int32_t ClientState::_internal_sat_num() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sat_num_;
}
inline void ClientState::_internal_set_sat_num(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sat_num_ = value;
}

// double diff = 18;
inline void ClientState::clear_diff() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.diff_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00020000U);
}
inline double ClientState::diff() const {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.diff)
  return _internal_diff();
}
inline void ClientState::set_diff(double value) {
  _internal_set_diff(value);
  SetHasBit(_impl_._has_bits_[0], 0x00020000U);
  // @@protoc_insertion_point(field_set:caster.core.ClientState.diff)
}
inline double ClientState::_internal_diff() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.diff_;
}
inline void ClientState::_internal_set_diff(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.diff_ = value;
}

// double distance = 19;
inline void ClientState::clear_distance() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.distance_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00040000U);
}
inline double ClientState::distance() const {
  // @@protoc_insertion_point(field_get:caster.core.ClientState.distance)
  return _internal_distance();
}
inline void ClientState::set_distance(double value) {
  _internal_set_distance(value);
  SetHasBit(_impl_._has_bits_[0], 0x00040000U);
  // @@protoc_insertion_point(field_set:caster.core.ClientState.distance)
}
inline double ClientState::_internal_distance() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.distance_;
}
inline void ClientState::_internal_set_distance(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.distance_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace core
}  // namespace caster


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // core_2fClientState_2eproto_2epb_2eh
