// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/ServerState.proto
// Protobuf C++ Version: 7.35.0-dev

#ifndef core_2fServerState_2eproto_2epb_2eh
#define core_2fServerState_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_core_2fServerState_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_core_2fServerState_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_core_2fServerState_2eproto;
}  // extern "C"
namespace caster {
namespace core {
enum ServerInfoFromType : int;
extern const uint32_t ServerInfoFromType_internal_data_[];
class ServerState;
struct ServerStateGlobalsTypeInternal;
extern ServerStateGlobalsTypeInternal _ServerState_globals_;
extern const ::google::protobuf::internal::ClassDataFull ServerState_class_data_;
}  // namespace core
}  // namespace caster
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::caster::core::ServerInfoFromType_internal_data_>
    internal::EnumTraitsImpl::value<::caster::core::ServerInfoFromType>;
}  // namespace protobuf
}  // namespace google

namespace caster {
namespace core {
enum ServerInfoFromType : int {
  SERVER_INFO_FROM_UNKNOWN = 0,
  SERVER_INFO_FROM_DECODE = 1,
  SERVER_INFO_FROM_SOURCE = 2,
  ServerInfoFromType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  ServerInfoFromType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ServerInfoFromType_internal_data_[];
inline constexpr ServerInfoFromType ServerInfoFromType_MIN =
    static_cast<ServerInfoFromType>(0);
inline constexpr ServerInfoFromType ServerInfoFromType_MAX =
    static_cast<ServerInfoFromType>(2);
[[nodiscard]] inline bool ServerInfoFromType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int ServerInfoFromType_ARRAYSIZE = 2 + 1;
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
ServerInfoFromType_descriptor();
[[nodiscard]] inline auto ProtobufInternalGetEnumDescriptor(ServerInfoFromType) {
  return ServerInfoFromType_descriptor();
}
template <typename T>
[[nodiscard]] const ::std::string& ServerInfoFromType_Name(T value) {
  static_assert(::std::is_same<T, ServerInfoFromType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ServerInfoFromType_Name().");
  return ServerInfoFromType_Name(static_cast<ServerInfoFromType>(value));
}
template <>
[[nodiscard]] inline const ::std::string& ServerInfoFromType_Name(ServerInfoFromType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ServerInfoFromType_descriptor, 0, 2>(
      static_cast<int>(value));
}
[[nodiscard]] inline bool ServerInfoFromType_Parse(
    ::absl::string_view name, ServerInfoFromType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ServerInfoFromType>(ServerInfoFromType_descriptor(), name,
                                           value);
}
using ::google::protobuf::internal::generated_enum::AbslParseFlag;
using ::google::protobuf::internal::generated_enum::AbslUnparseFlag;

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED ServerState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:caster.core.ServerState) */ {
 public:
  inline ServerState() : ServerState(nullptr) {}
  ~ServerState() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ServerState* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ServerState));
  }
#endif

  template <typename = void>
  explicit constexpr ServerState(::google::protobuf::internal::ConstantInitialized);

  inline ServerState(const ServerState& from) : ServerState(nullptr, from) {}
  inline ServerState(ServerState&& from) noexcept
      : ServerState(nullptr, ::std::move(from)) {}
  inline ServerState& operator=(const ServerState& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerState& operator=(ServerState&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const ServerState& default_instance() {
    return *reinterpret_cast<const ServerState*>(&_ServerState_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ServerState& a, ServerState& b) { a.Swap(&b); }
  inline void Swap(ServerState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] ServerState* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ServerState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ServerState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ServerState& from) { ServerState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ServerState* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "caster.core.ServerState"; }

  explicit ServerState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ServerState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ServerState& from);
  ServerState(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ServerState&& from) noexcept
      : ServerState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUidFieldNumber = 1,
    kMountpointFieldNumber = 5,
    kIdentufierFieldNumber = 6,
    kFormatFieldNumber = 7,
    kFormatDetailsFieldNumber = 8,
    kCarrierFieldNumber = 9,
    kNavSystemFieldNumber = 10,
    kNetworkFieldNumber = 11,
    kCountryFieldNumber = 12,
    kLatitudeFieldNumber = 13,
    kLongitudeFieldNumber = 14,
    kNmeaFieldNumber = 15,
    kSolutionFieldNumber = 16,
    kGeneratorFieldNumber = 17,
    kComprEncrrypFieldNumber = 18,
    kAuthenticationFieldNumber = 19,
    kFeeFieldNumber = 20,
    kBitrateFieldNumber = 21,
    kMiscFieldNumber = 22,
    kCreateTimeFieldNumber = 2,
    kUpdateTimeFieldNumber = 3,
    kTypeFieldNumber = 4,
  };
  // string uid = 1;
  void clear_uid() ;
  [[nodiscard]] const ::std::string& uid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_uid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_uid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_uid();
  void set_allocated_uid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_uid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_uid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_uid();

  public:
  // string mountpoint = 5;
  void clear_mountpoint() ;
  [[nodiscard]] const ::std::string& mountpoint() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_mountpoint(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_mountpoint();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_mountpoint();
  void set_allocated_mountpoint(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_mountpoint() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_mountpoint(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_mountpoint();

  public:
  // string identufier = 6;
  void clear_identufier() ;
  [[nodiscard]] const ::std::string& identufier() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_identufier(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_identufier();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_identufier();
  void set_allocated_identufier(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_identufier() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_identufier(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_identufier();

  public:
  // string format = 7;
  void clear_format() ;
  [[nodiscard]] const ::std::string& format() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_format(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_format();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_format();
  void set_allocated_format(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_format() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_format(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_format();

  public:
  // string format_details = 8;
  void clear_format_details() ;
  [[nodiscard]] const ::std::string& format_details() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_format_details(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_format_details();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_format_details();
  void set_allocated_format_details(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_format_details() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_format_details(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_format_details();

  public:
  // string carrier = 9;
  void clear_carrier() ;
  [[nodiscard]] const ::std::string& carrier() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_carrier(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_carrier();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_carrier();
  void set_allocated_carrier(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_carrier() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_carrier(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_carrier();

  public:
  // string nav_system = 10;
  void clear_nav_system() ;
  [[nodiscard]] const ::std::string& nav_system() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_nav_system(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_nav_system();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_nav_system();
  void set_allocated_nav_system(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_nav_system() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nav_system(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_nav_system();

  public:
  // string network = 11;
  void clear_network() ;
  [[nodiscard]] const ::std::string& network() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_network(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_network();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_network();
  void set_allocated_network(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_network() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_network(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_network();

  public:
  // string country = 12;
  void clear_country() ;
  [[nodiscard]] const ::std::string& country() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_country(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_country();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_country();
  void set_allocated_country(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_country() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_country(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_country();

  public:
  // string latitude = 13;
  void clear_latitude() ;
  [[nodiscard]] const ::std::string& latitude() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_latitude(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_latitude();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_latitude();
  void set_allocated_latitude(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_latitude() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_latitude(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_latitude();

  public:
  // string longitude = 14;
  void clear_longitude() ;
  [[nodiscard]] const ::std::string& longitude() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_longitude(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_longitude();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_longitude();
  void set_allocated_longitude(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_longitude() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_longitude(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_longitude();

  public:
  // string nmea = 15;
  void clear_nmea() ;
  [[nodiscard]] const ::std::string& nmea() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_nmea(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_nmea();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_nmea();
  void set_allocated_nmea(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_nmea() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nmea(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_nmea();

  public:
  // string solution = 16;
  void clear_solution() ;
  [[nodiscard]] const ::std::string& solution() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_solution(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_solution();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_solution();
  void set_allocated_solution(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_solution() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_solution(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_solution();

  public:
  // string generator = 17;
  void clear_generator() ;
  [[nodiscard]] const ::std::string& generator() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_generator(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_generator();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_generator();
  void set_allocated_generator(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_generator() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_generator(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_generator();

  public:
  // string compr_encrryp = 18;
  void clear_compr_encrryp() ;
  [[nodiscard]] const ::std::string& compr_encrryp() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_compr_encrryp(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_compr_encrryp();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_compr_encrryp();
  void set_allocated_compr_encrryp(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_compr_encrryp() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_compr_encrryp(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_compr_encrryp();

  public:
  // string authentication = 19;
  void clear_authentication() ;
  [[nodiscard]] const ::std::string& authentication() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_authentication(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_authentication();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_authentication();
  void set_allocated_authentication(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_authentication() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_authentication(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_authentication();

  public:
  // string fee = 20;
  void clear_fee() ;
  [[nodiscard]] const ::std::string& fee() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_fee(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_fee();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_fee();
  void set_allocated_fee(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_fee() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_fee(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_fee();

  public:
  // string bitrate = 21;
  void clear_bitrate() ;
  [[nodiscard]] const ::std::string& bitrate() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_bitrate(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_bitrate();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_bitrate();
  void set_allocated_bitrate(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_bitrate() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_bitrate(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_bitrate();

  public:
  // string misc = 22;
  void clear_misc() ;
  [[nodiscard]] const ::std::string& misc() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_misc(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_misc();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_misc();
  void set_allocated_misc(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_misc() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_misc(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_misc();

  public:
  // uint64 create_time = 2;
  void clear_create_time() ;
  [[nodiscard]] ::uint64_t create_time() const;
  void set_create_time(::uint64_t value);

  private:
  ::uint64_t _internal_create_time() const;
  void _internal_set_create_time(::uint64_t value);

  public:
  // uint64 update_time = 3;
  void clear_update_time() ;
  [[nodiscard]] ::uint64_t update_time() const;
  void set_update_time(::uint64_t value);

  private:
  ::uint64_t _internal_update_time() const;
  void _internal_set_update_time(::uint64_t value);

  public:
  // .caster.core.ServerInfoFromType type = 4;
  void clear_type() ;
  [[nodiscard]] ::caster::core::ServerInfoFromType type() const;
  void set_type(::caster::core::ServerInfoFromType value);

  private:
  ::caster::core::ServerInfoFromType _internal_type() const;
  void _internal_set_type(::caster::core::ServerInfoFromType value);

  public:
  // @@protoc_insertion_point(class_scope:caster.core.ServerState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<5, 22,
                                   0, 201,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ServerState& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr uid_;
    ::google::protobuf::internal::ArenaStringPtr mountpoint_;
    ::google::protobuf::internal::ArenaStringPtr identufier_;
    ::google::protobuf::internal::ArenaStringPtr format_;
    ::google::protobuf::internal::ArenaStringPtr format_details_;
    ::google::protobuf::internal::ArenaStringPtr carrier_;
    ::google::protobuf::internal::ArenaStringPtr nav_system_;
    ::google::protobuf::internal::ArenaStringPtr network_;
    ::google::protobuf::internal::ArenaStringPtr country_;
    ::google::protobuf::internal::ArenaStringPtr latitude_;
    ::google::protobuf::internal::ArenaStringPtr longitude_;
    ::google::protobuf::internal::ArenaStringPtr nmea_;
    ::google::protobuf::internal::ArenaStringPtr solution_;
    ::google::protobuf::internal::ArenaStringPtr generator_;
    ::google::protobuf::internal::ArenaStringPtr compr_encrryp_;
    ::google::protobuf::internal::ArenaStringPtr authentication_;
    ::google::protobuf::internal::ArenaStringPtr fee_;
    ::google::protobuf::internal::ArenaStringPtr bitrate_;
    ::google::protobuf::internal::ArenaStringPtr misc_;
    ::uint64_t create_time_;
    ::uint64_t update_time_;
    int type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_core_2fServerState_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ServerState_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ServerState

// string uid = 1;
inline void ServerState::clear_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& ServerState::uid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.uid)
  return _internal_uid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_uid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.uid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.uid)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_uid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_uid();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.uid)
  return _s;
}
inline const ::std::string& ServerState::_internal_uid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uid_.Get();
}
inline void ServerState::_internal_set_uid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.uid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.uid)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.uid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.uid_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_uid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.uid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.uid_.IsDefault()) {
    _impl_.uid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.uid)
}

// uint64 create_time = 2;
inline void ServerState::clear_create_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.create_time_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00080000U);
}
inline ::uint64_t ServerState::create_time() const {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.create_time)
  return _internal_create_time();
}
inline void ServerState::set_create_time(::uint64_t value) {
  _internal_set_create_time(value);
  SetHasBit(_impl_._has_bits_[0], 0x00080000U);
  // @@protoc_insertion_point(field_set:caster.core.ServerState.create_time)
}
inline ::uint64_t ServerState::_internal_create_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.create_time_;
}
inline void ServerState::_internal_set_create_time(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.create_time_ = value;
}

// uint64 update_time = 3;
inline void ServerState::clear_update_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.update_time_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00100000U);
}
inline ::uint64_t ServerState::update_time() const {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.update_time)
  return _internal_update_time();
}
inline void ServerState::set_update_time(::uint64_t value) {
  _internal_set_update_time(value);
  SetHasBit(_impl_._has_bits_[0], 0x00100000U);
  // @@protoc_insertion_point(field_set:caster.core.ServerState.update_time)
}
inline ::uint64_t ServerState::_internal_update_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.update_time_;
}
inline void ServerState::_internal_set_update_time(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.update_time_ = value;
}

// .caster.core.ServerInfoFromType type = 4;
inline void ServerState::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00200000U);
}
inline ::caster::core::ServerInfoFromType ServerState::type() const {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.type)
  return _internal_type();
}
inline void ServerState::set_type(::caster::core::ServerInfoFromType value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00200000U);
  // @@protoc_insertion_point(field_set:caster.core.ServerState.type)
}
inline ::caster::core::ServerInfoFromType ServerState::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::caster::core::ServerInfoFromType>(_impl_.type_);
}
inline void ServerState::_internal_set_type(::caster::core::ServerInfoFromType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// string mountpoint = 5;
inline void ServerState::clear_mountpoint() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mountpoint_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& ServerState::mountpoint() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.mountpoint)
  return _internal_mountpoint();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_mountpoint(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.mountpoint_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.mountpoint)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_mountpoint()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_mountpoint();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.mountpoint)
  return _s;
}
inline const ::std::string& ServerState::_internal_mountpoint() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mountpoint_.Get();
}
inline void ServerState::_internal_set_mountpoint(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mountpoint_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_mountpoint() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.mountpoint_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_mountpoint() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.mountpoint)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.mountpoint_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.mountpoint_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_mountpoint(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.mountpoint_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.mountpoint_.IsDefault()) {
    _impl_.mountpoint_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.mountpoint)
}

// string identufier = 6;
inline void ServerState::clear_identufier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identufier_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& ServerState::identufier() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.identufier)
  return _internal_identufier();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_identufier(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.identufier_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.identufier)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_identufier()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_identufier();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.identufier)
  return _s;
}
inline const ::std::string& ServerState::_internal_identufier() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.identufier_.Get();
}
inline void ServerState::_internal_set_identufier(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identufier_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_identufier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.identufier_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_identufier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.identufier)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.identufier_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.identufier_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_identufier(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.identufier_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.identufier_.IsDefault()) {
    _impl_.identufier_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.identufier)
}

// string format = 7;
inline void ServerState::clear_format() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.format_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& ServerState::format() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.format)
  return _internal_format();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_format(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.format_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.format)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_format()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_format();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.format)
  return _s;
}
inline const ::std::string& ServerState::_internal_format() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.format_.Get();
}
inline void ServerState::_internal_set_format(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.format_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_format() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.format_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_format() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.format)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.format_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.format_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_format(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.format_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.format_.IsDefault()) {
    _impl_.format_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.format)
}

// string format_details = 8;
inline void ServerState::clear_format_details() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.format_details_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::std::string& ServerState::format_details() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.format_details)
  return _internal_format_details();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_format_details(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.format_details_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.format_details)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_format_details()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::std::string* _s = _internal_mutable_format_details();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.format_details)
  return _s;
}
inline const ::std::string& ServerState::_internal_format_details() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.format_details_.Get();
}
inline void ServerState::_internal_set_format_details(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.format_details_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_format_details() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.format_details_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_format_details() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.format_details)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000010U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  auto* released = _impl_.format_details_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.format_details_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_format_details(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  _impl_.format_details_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.format_details_.IsDefault()) {
    _impl_.format_details_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.format_details)
}

// string carrier = 9;
inline void ServerState::clear_carrier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.carrier_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline const ::std::string& ServerState::carrier() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.carrier)
  return _internal_carrier();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_carrier(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  _impl_.carrier_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.carrier)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_carrier()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  ::std::string* _s = _internal_mutable_carrier();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.carrier)
  return _s;
}
inline const ::std::string& ServerState::_internal_carrier() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.carrier_.Get();
}
inline void ServerState::_internal_set_carrier(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.carrier_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_carrier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.carrier_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_carrier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.carrier)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000020U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  auto* released = _impl_.carrier_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.carrier_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_carrier(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  }
  _impl_.carrier_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.carrier_.IsDefault()) {
    _impl_.carrier_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.carrier)
}

// string nav_system = 10;
inline void ServerState::clear_nav_system() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nav_system_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline const ::std::string& ServerState::nav_system() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.nav_system)
  return _internal_nav_system();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_nav_system(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  _impl_.nav_system_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.nav_system)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_nav_system()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  ::std::string* _s = _internal_mutable_nav_system();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.nav_system)
  return _s;
}
inline const ::std::string& ServerState::_internal_nav_system() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nav_system_.Get();
}
inline void ServerState::_internal_set_nav_system(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nav_system_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_nav_system() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.nav_system_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_nav_system() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.nav_system)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000040U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
  auto* released = _impl_.nav_system_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nav_system_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_nav_system(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
  }
  _impl_.nav_system_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nav_system_.IsDefault()) {
    _impl_.nav_system_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.nav_system)
}

// string network = 11;
inline void ServerState::clear_network() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.network_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline const ::std::string& ServerState::network() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.network)
  return _internal_network();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_network(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  _impl_.network_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.network)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_network()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  ::std::string* _s = _internal_mutable_network();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.network)
  return _s;
}
inline const ::std::string& ServerState::_internal_network() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.network_.Get();
}
inline void ServerState::_internal_set_network(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.network_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_network() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.network_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_network() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.network)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000080U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
  auto* released = _impl_.network_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.network_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_network(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
  }
  _impl_.network_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.network_.IsDefault()) {
    _impl_.network_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.network)
}

// string country = 12;
inline void ServerState::clear_country() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.country_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline const ::std::string& ServerState::country() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.country)
  return _internal_country();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_country(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  _impl_.country_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.country)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_country()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  ::std::string* _s = _internal_mutable_country();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.country)
  return _s;
}
inline const ::std::string& ServerState::_internal_country() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.country_.Get();
}
inline void ServerState::_internal_set_country(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.country_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_country() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.country_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_country() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.country)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000100U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000100U);
  auto* released = _impl_.country_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.country_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_country(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000100U);
  }
  _impl_.country_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.country_.IsDefault()) {
    _impl_.country_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.country)
}

// string latitude = 13;
inline void ServerState::clear_latitude() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.latitude_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000200U);
}
inline const ::std::string& ServerState::latitude() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.latitude)
  return _internal_latitude();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_latitude(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  _impl_.latitude_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.latitude)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_latitude()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  ::std::string* _s = _internal_mutable_latitude();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.latitude)
  return _s;
}
inline const ::std::string& ServerState::_internal_latitude() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.latitude_.Get();
}
inline void ServerState::_internal_set_latitude(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.latitude_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_latitude() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.latitude_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_latitude() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.latitude)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000200U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000200U);
  auto* released = _impl_.latitude_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.latitude_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_latitude(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000200U);
  }
  _impl_.latitude_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.latitude_.IsDefault()) {
    _impl_.latitude_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.latitude)
}

// string longitude = 14;
inline void ServerState::clear_longitude() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.longitude_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000400U);
}
inline const ::std::string& ServerState::longitude() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.longitude)
  return _internal_longitude();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_longitude(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000400U);
  _impl_.longitude_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.longitude)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_longitude()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000400U);
  ::std::string* _s = _internal_mutable_longitude();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.longitude)
  return _s;
}
inline const ::std::string& ServerState::_internal_longitude() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.longitude_.Get();
}
inline void ServerState::_internal_set_longitude(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.longitude_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_longitude() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.longitude_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_longitude() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.longitude)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000400U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000400U);
  auto* released = _impl_.longitude_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.longitude_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_longitude(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000400U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000400U);
  }
  _impl_.longitude_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.longitude_.IsDefault()) {
    _impl_.longitude_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.longitude)
}

// string nmea = 15;
inline void ServerState::clear_nmea() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nmea_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000800U);
}
inline const ::std::string& ServerState::nmea() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.nmea)
  return _internal_nmea();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_nmea(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000800U);
  _impl_.nmea_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.nmea)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_nmea()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000800U);
  ::std::string* _s = _internal_mutable_nmea();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.nmea)
  return _s;
}
inline const ::std::string& ServerState::_internal_nmea() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nmea_.Get();
}
inline void ServerState::_internal_set_nmea(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nmea_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_nmea() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.nmea_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_nmea() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.nmea)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000800U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000800U);
  auto* released = _impl_.nmea_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nmea_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_nmea(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000800U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000800U);
  }
  _impl_.nmea_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nmea_.IsDefault()) {
    _impl_.nmea_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.nmea)
}

// string solution = 16;
inline void ServerState::clear_solution() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.solution_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00001000U);
}
inline const ::std::string& ServerState::solution() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.solution)
  return _internal_solution();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_solution(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00001000U);
  _impl_.solution_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.solution)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_solution()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00001000U);
  ::std::string* _s = _internal_mutable_solution();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.solution)
  return _s;
}
inline const ::std::string& ServerState::_internal_solution() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.solution_.Get();
}
inline void ServerState::_internal_set_solution(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.solution_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_solution() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.solution_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_solution() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.solution)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00001000U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00001000U);
  auto* released = _impl_.solution_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.solution_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_solution(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00001000U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00001000U);
  }
  _impl_.solution_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.solution_.IsDefault()) {
    _impl_.solution_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.solution)
}

// string generator = 17;
inline void ServerState::clear_generator() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.generator_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00002000U);
}
inline const ::std::string& ServerState::generator() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.generator)
  return _internal_generator();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_generator(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00002000U);
  _impl_.generator_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.generator)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_generator()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00002000U);
  ::std::string* _s = _internal_mutable_generator();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.generator)
  return _s;
}
inline const ::std::string& ServerState::_internal_generator() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.generator_.Get();
}
inline void ServerState::_internal_set_generator(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.generator_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_generator() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.generator_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_generator() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.generator)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00002000U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00002000U);
  auto* released = _impl_.generator_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.generator_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_generator(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00002000U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00002000U);
  }
  _impl_.generator_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.generator_.IsDefault()) {
    _impl_.generator_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.generator)
}

// string compr_encrryp = 18;
inline void ServerState::clear_compr_encrryp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.compr_encrryp_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00004000U);
}
inline const ::std::string& ServerState::compr_encrryp() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.compr_encrryp)
  return _internal_compr_encrryp();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_compr_encrryp(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00004000U);
  _impl_.compr_encrryp_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.compr_encrryp)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_compr_encrryp()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00004000U);
  ::std::string* _s = _internal_mutable_compr_encrryp();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.compr_encrryp)
  return _s;
}
inline const ::std::string& ServerState::_internal_compr_encrryp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.compr_encrryp_.Get();
}
inline void ServerState::_internal_set_compr_encrryp(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.compr_encrryp_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_compr_encrryp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.compr_encrryp_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_compr_encrryp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.compr_encrryp)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00004000U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00004000U);
  auto* released = _impl_.compr_encrryp_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.compr_encrryp_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_compr_encrryp(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00004000U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00004000U);
  }
  _impl_.compr_encrryp_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.compr_encrryp_.IsDefault()) {
    _impl_.compr_encrryp_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.compr_encrryp)
}

// string authentication = 19;
inline void ServerState::clear_authentication() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.authentication_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00008000U);
}
inline const ::std::string& ServerState::authentication() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.authentication)
  return _internal_authentication();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_authentication(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00008000U);
  _impl_.authentication_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.authentication)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_authentication()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00008000U);
  ::std::string* _s = _internal_mutable_authentication();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.authentication)
  return _s;
}
inline const ::std::string& ServerState::_internal_authentication() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.authentication_.Get();
}
inline void ServerState::_internal_set_authentication(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.authentication_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_authentication() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.authentication_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_authentication() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.authentication)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00008000U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00008000U);
  auto* released = _impl_.authentication_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.authentication_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_authentication(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00008000U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00008000U);
  }
  _impl_.authentication_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.authentication_.IsDefault()) {
    _impl_.authentication_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.authentication)
}

// string fee = 20;
inline void ServerState::clear_fee() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fee_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00010000U);
}
inline const ::std::string& ServerState::fee() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.fee)
  return _internal_fee();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_fee(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00010000U);
  _impl_.fee_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.fee)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_fee()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00010000U);
  ::std::string* _s = _internal_mutable_fee();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.fee)
  return _s;
}
inline const ::std::string& ServerState::_internal_fee() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fee_.Get();
}
inline void ServerState::_internal_set_fee(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fee_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_fee() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.fee_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_fee() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.fee)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00010000U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00010000U);
  auto* released = _impl_.fee_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.fee_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_fee(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00010000U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00010000U);
  }
  _impl_.fee_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.fee_.IsDefault()) {
    _impl_.fee_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.fee)
}

// string bitrate = 21;
inline void ServerState::clear_bitrate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bitrate_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00020000U);
}
inline const ::std::string& ServerState::bitrate() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.bitrate)
  return _internal_bitrate();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_bitrate(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00020000U);
  _impl_.bitrate_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.bitrate)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_bitrate()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00020000U);
  ::std::string* _s = _internal_mutable_bitrate();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.bitrate)
  return _s;
}
inline const ::std::string& ServerState::_internal_bitrate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bitrate_.Get();
}
inline void ServerState::_internal_set_bitrate(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bitrate_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_bitrate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.bitrate_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_bitrate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.bitrate)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00020000U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00020000U);
  auto* released = _impl_.bitrate_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.bitrate_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_bitrate(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00020000U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00020000U);
  }
  _impl_.bitrate_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.bitrate_.IsDefault()) {
    _impl_.bitrate_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.bitrate)
}

// string misc = 22;
inline void ServerState::clear_misc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.misc_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00040000U);
}
inline const ::std::string& ServerState::misc() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.core.ServerState.misc)
  return _internal_misc();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ServerState::set_misc(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00040000U);
  _impl_.misc_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.core.ServerState.misc)
}
inline ::std::string* PROTOBUF_NONNULL ServerState::mutable_misc()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00040000U);
  ::std::string* _s = _internal_mutable_misc();
  // @@protoc_insertion_point(field_mutable:caster.core.ServerState.misc)
  return _s;
}
inline const ::std::string& ServerState::_internal_misc() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.misc_.Get();
}
inline void ServerState::_internal_set_misc(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.misc_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ServerState::_internal_mutable_misc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.misc_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ServerState::release_misc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.core.ServerState.misc)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00040000U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00040000U);
  auto* released = _impl_.misc_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.misc_.Set("", GetArena());
  }
  return released;
}
inline void ServerState::set_allocated_misc(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00040000U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00040000U);
  }
  _impl_.misc_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.misc_.IsDefault()) {
    _impl_.misc_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.core.ServerState.misc)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace core
}  // namespace caster


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::caster::core::ServerInfoFromType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::caster::core::ServerInfoFromType>() {
  return ::caster::core::ServerInfoFromType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // core_2fServerState_2eproto_2epb_2eh
