// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: context/info_mpt.proto
// Protobuf C++ Version: 7.35.0-dev

#ifndef context_2finfo_5fmpt_2eproto_2epb_2eh
#define context_2finfo_5fmpt_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_context_2finfo_5fmpt_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_context_2finfo_5fmpt_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_context_2finfo_5fmpt_2eproto;
}  // extern "C"
namespace caster {
namespace context {
class MptInfo;
struct MptInfoGlobalsTypeInternal;
extern MptInfoGlobalsTypeInternal _MptInfo_globals_;
extern const ::google::protobuf::internal::ClassDataFull MptInfo_class_data_;
}  // namespace context
}  // namespace caster
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace caster {
namespace context {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED MptInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:caster.context.MptInfo) */ {
 public:
  inline MptInfo() : MptInfo(nullptr) {}
  ~MptInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MptInfo* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MptInfo));
  }
#endif

  template <typename = void>
  explicit constexpr MptInfo(::google::protobuf::internal::ConstantInitialized);

  inline MptInfo(const MptInfo& from) : MptInfo(nullptr, from) {}
  inline MptInfo(MptInfo&& from) noexcept
      : MptInfo(nullptr, ::std::move(from)) {}
  inline MptInfo& operator=(const MptInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline MptInfo& operator=(MptInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const MptInfo& default_instance() {
    return *reinterpret_cast<const MptInfo*>(&_MptInfo_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(MptInfo& a, MptInfo& b) { a.Swap(&b); }
  inline void Swap(MptInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MptInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] MptInfo* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MptInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MptInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MptInfo& from) { MptInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MptInfo* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "caster.context.MptInfo"; }

  explicit MptInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MptInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MptInfo& from);
  MptInfo(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MptInfo&& from) noexcept
      : MptInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUidFieldNumber = 1,
    kLoginUserFieldNumber = 4,
    kLoginIpFieldNumber = 5,
    kLoginPortFieldNumber = 6,
    kCreateTimeFieldNumber = 2,
    kUpdateTimeFieldNumber = 3,
    kOptHeddenFieldNumber = 7,
    kOptDisableFieldNumber = 8,
    kOptDecodeFieldNumber = 9,
    kOptGroupTypeFieldNumber = 10,
  };
  // string uid = 1;
  void clear_uid() ;
  [[nodiscard]] const ::std::string& uid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_uid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_uid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_uid();
  void set_allocated_uid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_uid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_uid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_uid();

  public:
  // string login_user = 4;
  void clear_login_user() ;
  [[nodiscard]] const ::std::string& login_user() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_login_user(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_login_user();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_login_user();
  void set_allocated_login_user(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_login_user() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_login_user(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_login_user();

  public:
  // string login_ip = 5;
  void clear_login_ip() ;
  [[nodiscard]] const ::std::string& login_ip() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_login_ip(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_login_ip();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_login_ip();
  void set_allocated_login_ip(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_login_ip() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_login_ip(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_login_ip();

  public:
  // string login_port = 6;
  void clear_login_port() ;
  [[nodiscard]] const ::std::string& login_port() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_login_port(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_login_port();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_login_port();
  void set_allocated_login_port(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_login_port() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_login_port(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_login_port();

  public:
  // uint64 create_time = 2;
  void clear_create_time() ;
  [[nodiscard]] ::uint64_t create_time() const;
  void set_create_time(::uint64_t value);

  private:
  ::uint64_t _internal_create_time() const;
  void _internal_set_create_time(::uint64_t value);

  public:
  // uint64 update_time = 3;
  void clear_update_time() ;
  [[nodiscard]] ::uint64_t update_time() const;
  void set_update_time(::uint64_t value);

  private:
  ::uint64_t _internal_update_time() const;
  void _internal_set_update_time(::uint64_t value);

  public:
  // int32 opt_hedden = 7;
  void clear_opt_hedden() ;
  [[nodiscard]] ::int32_t opt_hedden() const;
  void set_opt_hedden(::int32_t value);

  private:
  ::int32_t _internal_opt_hedden() const;
  void _internal_set_opt_hedden(::int32_t value);

  public:
  // int32 opt_disable = 8;
  void clear_opt_disable() ;
  [[nodiscard]] ::int32_t opt_disable() const;
  void set_opt_disable(::int32_t value);

  private:
  ::int32_t _internal_opt_disable() const;
  void _internal_set_opt_disable(::int32_t value);

  public:
  // int32 opt_decode = 9;
  void clear_opt_decode() ;
  [[nodiscard]] ::int32_t opt_decode() const;
  void set_opt_decode(::int32_t value);

  private:
  ::int32_t _internal_opt_decode() const;
  void _internal_set_opt_decode(::int32_t value);

  public:
  // int32 opt_group_type = 10;
  void clear_opt_group_type() ;
  [[nodiscard]] ::int32_t opt_group_type() const;
  void set_opt_group_type(::int32_t value);

  private:
  ::int32_t _internal_opt_group_type() const;
  void _internal_set_opt_group_type(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:caster.context.MptInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 10,
                                   0, 70,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MptInfo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr uid_;
    ::google::protobuf::internal::ArenaStringPtr login_user_;
    ::google::protobuf::internal::ArenaStringPtr login_ip_;
    ::google::protobuf::internal::ArenaStringPtr login_port_;
    ::uint64_t create_time_;
    ::uint64_t update_time_;
    ::int32_t opt_hedden_;
    ::int32_t opt_disable_;
    ::int32_t opt_decode_;
    ::int32_t opt_group_type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_context_2finfo_5fmpt_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MptInfo_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MptInfo

// string uid = 1;
inline void MptInfo::clear_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& MptInfo::uid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.context.MptInfo.uid)
  return _internal_uid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MptInfo::set_uid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.uid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.context.MptInfo.uid)
}
inline ::std::string* PROTOBUF_NONNULL MptInfo::mutable_uid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_uid();
  // @@protoc_insertion_point(field_mutable:caster.context.MptInfo.uid)
  return _s;
}
inline const ::std::string& MptInfo::_internal_uid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uid_.Get();
}
inline void MptInfo::_internal_set_uid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MptInfo::_internal_mutable_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.uid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MptInfo::release_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.context.MptInfo.uid)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.uid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.uid_.Set("", GetArena());
  }
  return released;
}
inline void MptInfo::set_allocated_uid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.uid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.uid_.IsDefault()) {
    _impl_.uid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.context.MptInfo.uid)
}

// uint64 create_time = 2;
inline void MptInfo::clear_create_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.create_time_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint64_t MptInfo::create_time() const {
  // @@protoc_insertion_point(field_get:caster.context.MptInfo.create_time)
  return _internal_create_time();
}
inline void MptInfo::set_create_time(::uint64_t value) {
  _internal_set_create_time(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:caster.context.MptInfo.create_time)
}
inline ::uint64_t MptInfo::_internal_create_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.create_time_;
}
inline void MptInfo::_internal_set_create_time(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.create_time_ = value;
}

// uint64 update_time = 3;
inline void MptInfo::clear_update_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.update_time_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::uint64_t MptInfo::update_time() const {
  // @@protoc_insertion_point(field_get:caster.context.MptInfo.update_time)
  return _internal_update_time();
}
inline void MptInfo::set_update_time(::uint64_t value) {
  _internal_set_update_time(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:caster.context.MptInfo.update_time)
}
inline ::uint64_t MptInfo::_internal_update_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.update_time_;
}
inline void MptInfo::_internal_set_update_time(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.update_time_ = value;
}

// string login_user = 4;
inline void MptInfo::clear_login_user() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.login_user_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& MptInfo::login_user() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.context.MptInfo.login_user)
  return _internal_login_user();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MptInfo::set_login_user(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.login_user_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.context.MptInfo.login_user)
}
inline ::std::string* PROTOBUF_NONNULL MptInfo::mutable_login_user()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_login_user();
  // @@protoc_insertion_point(field_mutable:caster.context.MptInfo.login_user)
  return _s;
}
inline const ::std::string& MptInfo::_internal_login_user() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.login_user_.Get();
}
inline void MptInfo::_internal_set_login_user(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.login_user_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MptInfo::_internal_mutable_login_user() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.login_user_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MptInfo::release_login_user() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.context.MptInfo.login_user)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.login_user_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.login_user_.Set("", GetArena());
  }
  return released;
}
inline void MptInfo::set_allocated_login_user(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.login_user_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.login_user_.IsDefault()) {
    _impl_.login_user_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.context.MptInfo.login_user)
}

// string login_ip = 5;
inline void MptInfo::clear_login_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.login_ip_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& MptInfo::login_ip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.context.MptInfo.login_ip)
  return _internal_login_ip();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MptInfo::set_login_ip(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.login_ip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.context.MptInfo.login_ip)
}
inline ::std::string* PROTOBUF_NONNULL MptInfo::mutable_login_ip()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_login_ip();
  // @@protoc_insertion_point(field_mutable:caster.context.MptInfo.login_ip)
  return _s;
}
inline const ::std::string& MptInfo::_internal_login_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.login_ip_.Get();
}
inline void MptInfo::_internal_set_login_ip(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.login_ip_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MptInfo::_internal_mutable_login_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.login_ip_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MptInfo::release_login_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.context.MptInfo.login_ip)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.login_ip_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.login_ip_.Set("", GetArena());
  }
  return released;
}
inline void MptInfo::set_allocated_login_ip(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.login_ip_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.login_ip_.IsDefault()) {
    _impl_.login_ip_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.context.MptInfo.login_ip)
}

// string login_port = 6;
inline void MptInfo::clear_login_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.login_port_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& MptInfo::login_port() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.context.MptInfo.login_port)
  return _internal_login_port();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MptInfo::set_login_port(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.login_port_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.context.MptInfo.login_port)
}
inline ::std::string* PROTOBUF_NONNULL MptInfo::mutable_login_port()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_login_port();
  // @@protoc_insertion_point(field_mutable:caster.context.MptInfo.login_port)
  return _s;
}
inline const ::std::string& MptInfo::_internal_login_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.login_port_.Get();
}
inline void MptInfo::_internal_set_login_port(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.login_port_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL MptInfo::_internal_mutable_login_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.login_port_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE MptInfo::release_login_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.context.MptInfo.login_port)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.login_port_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.login_port_.Set("", GetArena());
  }
  return released;
}
inline void MptInfo::set_allocated_login_port(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.login_port_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.login_port_.IsDefault()) {
    _impl_.login_port_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.context.MptInfo.login_port)
}

// int32 opt_hedden = 7;
inline void MptInfo::clear_opt_hedden() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.opt_hedden_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::int32_t MptInfo::opt_hedden() const {
  // @@protoc_insertion_point(field_get:caster.context.MptInfo.opt_hedden)
  return _internal_opt_hedden();
}
inline void MptInfo::set_opt_hedden(::int32_t value) {
  _internal_set_opt_hedden(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:caster.context.MptInfo.opt_hedden)
}
inline ::int32_t MptInfo::_internal_opt_hedden() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.opt_hedden_;
}
inline void MptInfo::_internal_set_opt_hedden(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.opt_hedden_ = value;
}

// int32 opt_disable = 8;
inline void MptInfo::clear_opt_disable() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.opt_disable_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::int32_t MptInfo::opt_disable() const {
  // @@protoc_insertion_point(field_get:caster.context.MptInfo.opt_disable)
  return _internal_opt_disable();
}
inline void MptInfo::set_opt_disable(::int32_t value) {
  _internal_set_opt_disable(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:caster.context.MptInfo.opt_disable)
}
inline ::int32_t MptInfo::_internal_opt_disable() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.opt_disable_;
}
inline void MptInfo::_internal_set_opt_disable(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.opt_disable_ = value;
}

// int32 opt_decode = 9;
inline void MptInfo::clear_opt_decode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.opt_decode_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline ::int32_t MptInfo::opt_decode() const {
  // @@protoc_insertion_point(field_get:caster.context.MptInfo.opt_decode)
  return _internal_opt_decode();
}
inline void MptInfo::set_opt_decode(::int32_t value) {
  _internal_set_opt_decode(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:caster.context.MptInfo.opt_decode)
}
inline ::int32_t MptInfo::_internal_opt_decode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.opt_decode_;
}
inline void MptInfo::_internal_set_opt_decode(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.opt_decode_ = value;
}

// int32 opt_group_type = 10;
inline void MptInfo::clear_opt_group_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.opt_group_type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000200U);
}
inline ::int32_t MptInfo::opt_group_type() const {
  // @@protoc_insertion_point(field_get:caster.context.MptInfo.opt_group_type)
  return _internal_opt_group_type();
}
inline void MptInfo::set_opt_group_type(::int32_t value) {
  _internal_set_opt_group_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_set:caster.context.MptInfo.opt_group_type)
}
inline ::int32_t MptInfo::_internal_opt_group_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.opt_group_type_;
}
inline void MptInfo::_internal_set_opt_group_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.opt_group_type_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace context
}  // namespace caster


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // context_2finfo_5fmpt_2eproto_2epb_2eh
