// 数据推送信息
syntax = "proto3";
package caster.context;

enum ClientType {
  CLIENT_TYPE_UNKNOWN = 0;
  CLIENT_TYPE_COMMON  = 1;
  CLIENT_TYPE_NEAREST = 2;
  CLIENT_TYPE_PUSH    = 4;
  CLIENT_TYPE_PROXY   = 5;
  CLIENT_TYPE_GRID    = 6;
}

message ClientInfo {
  string uid = 1;

  string login_mpt = 2; //  接入的挂载点
  string alias_mpt = 3; //内部提供数据的挂载点（真正使用的挂载点）

  ClientType type = 4; //接入类型

  string account = 5;
  string addr    = 6;
  int32  port    = 7;

  double online_time    = 8; // 上线时刻
  double online_seconds = 9; //上线持续时间

  double send_total = 10; // 总发送字节数
  double send_speed = 11; // 总发送速度
  double recv_total = 12; // 总接收字节数
  double recv_speed = 13; // 总接收速度

  int32 tcp_delay = 14; // TCP延迟

  double ecef_x               = 15;
  double ecef_y               = 16;
  double ecef_z               = 17;
  int32  quality              = 18;
  int32  sat_num              = 19;
  double diff                 = 20;
  double distance             = 21;
  double position_update_time = 22;

  double update_time = 23;
  double update_flag = 24;

//   uint64 create_time = 2; // 创建日期
//   uint64 update_time = 3; // 修改日期
}