// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/CasterNode.proto
// Protobuf C++ Version: 7.35.0-dev

#ifndef service_2fCasterNode_2eproto_2epb_2eh
#define service_2fCasterNode_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_service_2fCasterNode_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_service_2fCasterNode_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_service_2fCasterNode_2eproto;
}  // extern "C"
namespace caster {
namespace service {
class CasterNode;
struct CasterNodeGlobalsTypeInternal;
extern CasterNodeGlobalsTypeInternal _CasterNode_globals_;
extern const ::google::protobuf::internal::ClassDataFull CasterNode_class_data_;
}  // namespace service
}  // namespace caster
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace caster {
namespace service {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED CasterNode final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:caster.service.CasterNode) */ {
 public:
  inline CasterNode() : CasterNode(nullptr) {}
  ~CasterNode() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CasterNode* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CasterNode));
  }
#endif

  template <typename = void>
  explicit constexpr CasterNode(::google::protobuf::internal::ConstantInitialized);

  inline CasterNode(const CasterNode& from) : CasterNode(nullptr, from) {}
  inline CasterNode(CasterNode&& from) noexcept
      : CasterNode(nullptr, ::std::move(from)) {}
  inline CasterNode& operator=(const CasterNode& from) {
    CopyFrom(from);
    return *this;
  }
  inline CasterNode& operator=(CasterNode&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const CasterNode& default_instance() {
    return *reinterpret_cast<const CasterNode*>(&_CasterNode_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CasterNode& a, CasterNode& b) { a.Swap(&b); }
  inline void Swap(CasterNode* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CasterNode* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] CasterNode* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CasterNode>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CasterNode& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CasterNode& from) { CasterNode::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CasterNode* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "caster.service.CasterNode"; }

  explicit CasterNode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CasterNode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CasterNode& from);
  CasterNode(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CasterNode&& from) noexcept
      : CasterNode(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUidFieldNumber = 1,
    kNodeNameFieldNumber = 4,
    kSetVersionFieldNumber = 5,
    kTagVersionFieldNumber = 6,
    kRunPlatformFieldNumber = 14,
    kOnlineTimeFieldNumber = 2,
    kUpdateTimeFieldNumber = 3,
    kCpuUsageFieldNumber = 7,
    kMemUsageFieldNumber = 8,
    kQueueDelayFieldNumber = 9,
    kSubPingDelayFieldNumber = 10,
    kSubTcpDelayFieldNumber = 11,
    kPubPingDelayFieldNumber = 12,
    kPubTcpDelayFieldNumber = 13,
    kSendTotalFieldNumber = 15,
    kSendSpeedFieldNumber = 16,
    kRecvTotalFieldNumber = 17,
    kRecvSpeedFieldNumber = 18,
    kConnectCountFieldNumber = 19,
    kServerCountFieldNumber = 20,
    kClientCountFieldNumber = 21,
    kPullCountFieldNumber = 22,
    kPushCountFieldNumber = 23,
    kProxyCountFieldNumber = 24,
  };
  // string uid = 1;
  void clear_uid() ;
  [[nodiscard]] const ::std::string& uid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_uid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_uid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_uid();
  void set_allocated_uid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_uid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_uid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_uid();

  public:
  // string node_name = 4;
  void clear_node_name() ;
  [[nodiscard]] const ::std::string& node_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_node_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_node_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_node_name();
  void set_allocated_node_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_node_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_node_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_node_name();

  public:
  // string set_version = 5;
  void clear_set_version() ;
  [[nodiscard]] const ::std::string& set_version() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_set_version(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_set_version();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_set_version();
  void set_allocated_set_version(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_set_version() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_set_version(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_set_version();

  public:
  // string tag_version = 6;
  void clear_tag_version() ;
  [[nodiscard]] const ::std::string& tag_version() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_tag_version(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_tag_version();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_tag_version();
  void set_allocated_tag_version(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_tag_version() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_tag_version(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_tag_version();

  public:
  // string run_platform = 14;
  void clear_run_platform() ;
  [[nodiscard]] const ::std::string& run_platform() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_run_platform(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_run_platform();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_run_platform();
  void set_allocated_run_platform(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_run_platform() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_run_platform(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_run_platform();

  public:
  // uint64 online_time = 2;
  void clear_online_time() ;
  [[nodiscard]] ::uint64_t online_time() const;
  void set_online_time(::uint64_t value);

  private:
  ::uint64_t _internal_online_time() const;
  void _internal_set_online_time(::uint64_t value);

  public:
  // uint64 update_time = 3;
  void clear_update_time() ;
  [[nodiscard]] ::uint64_t update_time() const;
  void set_update_time(::uint64_t value);

  private:
  ::uint64_t _internal_update_time() const;
  void _internal_set_update_time(::uint64_t value);

  public:
  // double cpu_usage = 7;
  void clear_cpu_usage() ;
  [[nodiscard]] double cpu_usage() const;
  void set_cpu_usage(double value);

  private:
  double _internal_cpu_usage() const;
  void _internal_set_cpu_usage(double value);

  public:
  // uint64 mem_usage = 8;
  void clear_mem_usage() ;
  [[nodiscard]] ::uint64_t mem_usage() const;
  void set_mem_usage(::uint64_t value);

  private:
  ::uint64_t _internal_mem_usage() const;
  void _internal_set_mem_usage(::uint64_t value);

  public:
  // uint64 queue_delay = 9;
  void clear_queue_delay() ;
  [[nodiscard]] ::uint64_t queue_delay() const;
  void set_queue_delay(::uint64_t value);

  private:
  ::uint64_t _internal_queue_delay() const;
  void _internal_set_queue_delay(::uint64_t value);

  public:
  // uint64 sub_ping_delay = 10;
  void clear_sub_ping_delay() ;
  [[nodiscard]] ::uint64_t sub_ping_delay() const;
  void set_sub_ping_delay(::uint64_t value);

  private:
  ::uint64_t _internal_sub_ping_delay() const;
  void _internal_set_sub_ping_delay(::uint64_t value);

  public:
  // uint64 sub_tcp_delay = 11;
  void clear_sub_tcp_delay() ;
  [[nodiscard]] ::uint64_t sub_tcp_delay() const;
  void set_sub_tcp_delay(::uint64_t value);

  private:
  ::uint64_t _internal_sub_tcp_delay() const;
  void _internal_set_sub_tcp_delay(::uint64_t value);

  public:
  // uint64 pub_ping_delay = 12;
  void clear_pub_ping_delay() ;
  [[nodiscard]] ::uint64_t pub_ping_delay() const;
  void set_pub_ping_delay(::uint64_t value);

  private:
  ::uint64_t _internal_pub_ping_delay() const;
  void _internal_set_pub_ping_delay(::uint64_t value);

  public:
  // uint64 pub_tcp_delay = 13;
  void clear_pub_tcp_delay() ;
  [[nodiscard]] ::uint64_t pub_tcp_delay() const;
  void set_pub_tcp_delay(::uint64_t value);

  private:
  ::uint64_t _internal_pub_tcp_delay() const;
  void _internal_set_pub_tcp_delay(::uint64_t value);

  public:
  // uint64 send_total = 15;
  void clear_send_total() ;
  [[nodiscard]] ::uint64_t send_total() const;
  void set_send_total(::uint64_t value);

  private:
  ::uint64_t _internal_send_total() const;
  void _internal_set_send_total(::uint64_t value);

  public:
  // double send_speed = 16;
  void clear_send_speed() ;
  [[nodiscard]] double send_speed() const;
  void set_send_speed(double value);

  private:
  double _internal_send_speed() const;
  void _internal_set_send_speed(double value);

  public:
  // uint64 recv_total = 17;
  void clear_recv_total() ;
  [[nodiscard]] ::uint64_t recv_total() const;
  void set_recv_total(::uint64_t value);

  private:
  ::uint64_t _internal_recv_total() const;
  void _internal_set_recv_total(::uint64_t value);

  public:
  // double recv_speed = 18;
  void clear_recv_speed() ;
  [[nodiscard]] double recv_speed() const;
  void set_recv_speed(double value);

  private:
  double _internal_recv_speed() const;
  void _internal_set_recv_speed(double value);

  public:
  // uint32 connect_count = 19;
  void clear_connect_count() ;
  [[nodiscard]] ::uint32_t connect_count() const;
  void set_connect_count(::uint32_t value);

  private:
  ::uint32_t _internal_connect_count() const;
  void _internal_set_connect_count(::uint32_t value);

  public:
  // uint32 server_count = 20;
  void clear_server_count() ;
  [[nodiscard]] ::uint32_t server_count() const;
  void set_server_count(::uint32_t value);

  private:
  ::uint32_t _internal_server_count() const;
  void _internal_set_server_count(::uint32_t value);

  public:
  // uint32 client_count = 21;
  void clear_client_count() ;
  [[nodiscard]] ::uint32_t client_count() const;
  void set_client_count(::uint32_t value);

  private:
  ::uint32_t _internal_client_count() const;
  void _internal_set_client_count(::uint32_t value);

  public:
  // uint32 pull_count = 22;
  void clear_pull_count() ;
  [[nodiscard]] ::uint32_t pull_count() const;
  void set_pull_count(::uint32_t value);

  private:
  ::uint32_t _internal_pull_count() const;
  void _internal_set_pull_count(::uint32_t value);

  public:
  // uint32 push_count = 23;
  void clear_push_count() ;
  [[nodiscard]] ::uint32_t push_count() const;
  void set_push_count(::uint32_t value);

  private:
  ::uint32_t _internal_push_count() const;
  void _internal_set_push_count(::uint32_t value);

  public:
  // uint32 proxy_count = 24;
  void clear_proxy_count() ;
  [[nodiscard]] ::uint32_t proxy_count() const;
  void set_proxy_count(::uint32_t value);

  private:
  ::uint32_t _internal_proxy_count() const;
  void _internal_set_proxy_count(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:caster.service.CasterNode)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<5, 24,
                                   0, 104,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CasterNode& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr uid_;
    ::google::protobuf::internal::ArenaStringPtr node_name_;
    ::google::protobuf::internal::ArenaStringPtr set_version_;
    ::google::protobuf::internal::ArenaStringPtr tag_version_;
    ::google::protobuf::internal::ArenaStringPtr run_platform_;
    ::uint64_t online_time_;
    ::uint64_t update_time_;
    double cpu_usage_;
    ::uint64_t mem_usage_;
    ::uint64_t queue_delay_;
    ::uint64_t sub_ping_delay_;
    ::uint64_t sub_tcp_delay_;
    ::uint64_t pub_ping_delay_;
    ::uint64_t pub_tcp_delay_;
    ::uint64_t send_total_;
    double send_speed_;
    ::uint64_t recv_total_;
    double recv_speed_;
    ::uint32_t connect_count_;
    ::uint32_t server_count_;
    ::uint32_t client_count_;
    ::uint32_t pull_count_;
    ::uint32_t push_count_;
    ::uint32_t proxy_count_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_service_2fCasterNode_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CasterNode_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CasterNode

// string uid = 1;
inline void CasterNode::clear_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CasterNode::uid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.uid)
  return _internal_uid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CasterNode::set_uid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.uid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.uid)
}
inline ::std::string* PROTOBUF_NONNULL CasterNode::mutable_uid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_uid();
  // @@protoc_insertion_point(field_mutable:caster.service.CasterNode.uid)
  return _s;
}
inline const ::std::string& CasterNode::_internal_uid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uid_.Get();
}
inline void CasterNode::_internal_set_uid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CasterNode::_internal_mutable_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.uid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CasterNode::release_uid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.service.CasterNode.uid)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.uid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.uid_.Set("", GetArena());
  }
  return released;
}
inline void CasterNode::set_allocated_uid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.uid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.uid_.IsDefault()) {
    _impl_.uid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.service.CasterNode.uid)
}

// uint64 online_time = 2;
inline void CasterNode::clear_online_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.online_time_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::uint64_t CasterNode::online_time() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.online_time)
  return _internal_online_time();
}
inline void CasterNode::set_online_time(::uint64_t value) {
  _internal_set_online_time(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.online_time)
}
inline ::uint64_t CasterNode::_internal_online_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.online_time_;
}
inline void CasterNode::_internal_set_online_time(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.online_time_ = value;
}

// uint64 update_time = 3;
inline void CasterNode::clear_update_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.update_time_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::uint64_t CasterNode::update_time() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.update_time)
  return _internal_update_time();
}
inline void CasterNode::set_update_time(::uint64_t value) {
  _internal_set_update_time(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.update_time)
}
inline ::uint64_t CasterNode::_internal_update_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.update_time_;
}
inline void CasterNode::_internal_set_update_time(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.update_time_ = value;
}

// string node_name = 4;
inline void CasterNode::clear_node_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.node_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& CasterNode::node_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.node_name)
  return _internal_node_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CasterNode::set_node_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.node_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.node_name)
}
inline ::std::string* PROTOBUF_NONNULL CasterNode::mutable_node_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_node_name();
  // @@protoc_insertion_point(field_mutable:caster.service.CasterNode.node_name)
  return _s;
}
inline const ::std::string& CasterNode::_internal_node_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.node_name_.Get();
}
inline void CasterNode::_internal_set_node_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.node_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CasterNode::_internal_mutable_node_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.node_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CasterNode::release_node_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.service.CasterNode.node_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.node_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.node_name_.Set("", GetArena());
  }
  return released;
}
inline void CasterNode::set_allocated_node_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.node_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.node_name_.IsDefault()) {
    _impl_.node_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.service.CasterNode.node_name)
}

// string set_version = 5;
inline void CasterNode::clear_set_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.set_version_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& CasterNode::set_version() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.set_version)
  return _internal_set_version();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CasterNode::set_set_version(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.set_version_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.set_version)
}
inline ::std::string* PROTOBUF_NONNULL CasterNode::mutable_set_version()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_set_version();
  // @@protoc_insertion_point(field_mutable:caster.service.CasterNode.set_version)
  return _s;
}
inline const ::std::string& CasterNode::_internal_set_version() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.set_version_.Get();
}
inline void CasterNode::_internal_set_set_version(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.set_version_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CasterNode::_internal_mutable_set_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.set_version_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CasterNode::release_set_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.service.CasterNode.set_version)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.set_version_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.set_version_.Set("", GetArena());
  }
  return released;
}
inline void CasterNode::set_allocated_set_version(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.set_version_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.set_version_.IsDefault()) {
    _impl_.set_version_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.service.CasterNode.set_version)
}

// string tag_version = 6;
inline void CasterNode::clear_tag_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tag_version_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& CasterNode::tag_version() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.tag_version)
  return _internal_tag_version();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CasterNode::set_tag_version(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.tag_version_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.tag_version)
}
inline ::std::string* PROTOBUF_NONNULL CasterNode::mutable_tag_version()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_tag_version();
  // @@protoc_insertion_point(field_mutable:caster.service.CasterNode.tag_version)
  return _s;
}
inline const ::std::string& CasterNode::_internal_tag_version() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tag_version_.Get();
}
inline void CasterNode::_internal_set_tag_version(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tag_version_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CasterNode::_internal_mutable_tag_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.tag_version_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CasterNode::release_tag_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.service.CasterNode.tag_version)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.tag_version_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.tag_version_.Set("", GetArena());
  }
  return released;
}
inline void CasterNode::set_allocated_tag_version(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.tag_version_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.tag_version_.IsDefault()) {
    _impl_.tag_version_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.service.CasterNode.tag_version)
}

// double cpu_usage = 7;
inline void CasterNode::clear_cpu_usage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cpu_usage_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline double CasterNode::cpu_usage() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.cpu_usage)
  return _internal_cpu_usage();
}
inline void CasterNode::set_cpu_usage(double value) {
  _internal_set_cpu_usage(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.cpu_usage)
}
inline double CasterNode::_internal_cpu_usage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cpu_usage_;
}
inline void CasterNode::_internal_set_cpu_usage(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cpu_usage_ = value;
}

// uint64 mem_usage = 8;
inline void CasterNode::clear_mem_usage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mem_usage_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline ::uint64_t CasterNode::mem_usage() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.mem_usage)
  return _internal_mem_usage();
}
inline void CasterNode::set_mem_usage(::uint64_t value) {
  _internal_set_mem_usage(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.mem_usage)
}
inline ::uint64_t CasterNode::_internal_mem_usage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mem_usage_;
}
inline void CasterNode::_internal_set_mem_usage(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mem_usage_ = value;
}

// uint64 queue_delay = 9;
inline void CasterNode::clear_queue_delay() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.queue_delay_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000200U);
}
inline ::uint64_t CasterNode::queue_delay() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.queue_delay)
  return _internal_queue_delay();
}
inline void CasterNode::set_queue_delay(::uint64_t value) {
  _internal_set_queue_delay(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.queue_delay)
}
inline ::uint64_t CasterNode::_internal_queue_delay() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.queue_delay_;
}
inline void CasterNode::_internal_set_queue_delay(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.queue_delay_ = value;
}

// uint64 sub_ping_delay = 10;
inline void CasterNode::clear_sub_ping_delay() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sub_ping_delay_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000400U);
}
inline ::uint64_t CasterNode::sub_ping_delay() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.sub_ping_delay)
  return _internal_sub_ping_delay();
}
inline void CasterNode::set_sub_ping_delay(::uint64_t value) {
  _internal_set_sub_ping_delay(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000400U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.sub_ping_delay)
}
inline ::uint64_t CasterNode::_internal_sub_ping_delay() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sub_ping_delay_;
}
inline void CasterNode::_internal_set_sub_ping_delay(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sub_ping_delay_ = value;
}

// uint64 sub_tcp_delay = 11;
inline void CasterNode::clear_sub_tcp_delay() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sub_tcp_delay_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000800U);
}
inline ::uint64_t CasterNode::sub_tcp_delay() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.sub_tcp_delay)
  return _internal_sub_tcp_delay();
}
inline void CasterNode::set_sub_tcp_delay(::uint64_t value) {
  _internal_set_sub_tcp_delay(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000800U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.sub_tcp_delay)
}
inline ::uint64_t CasterNode::_internal_sub_tcp_delay() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sub_tcp_delay_;
}
inline void CasterNode::_internal_set_sub_tcp_delay(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sub_tcp_delay_ = value;
}

// uint64 pub_ping_delay = 12;
inline void CasterNode::clear_pub_ping_delay() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pub_ping_delay_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00001000U);
}
inline ::uint64_t CasterNode::pub_ping_delay() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.pub_ping_delay)
  return _internal_pub_ping_delay();
}
inline void CasterNode::set_pub_ping_delay(::uint64_t value) {
  _internal_set_pub_ping_delay(value);
  SetHasBit(_impl_._has_bits_[0], 0x00001000U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.pub_ping_delay)
}
inline ::uint64_t CasterNode::_internal_pub_ping_delay() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pub_ping_delay_;
}
inline void CasterNode::_internal_set_pub_ping_delay(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pub_ping_delay_ = value;
}

// uint64 pub_tcp_delay = 13;
inline void CasterNode::clear_pub_tcp_delay() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pub_tcp_delay_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00002000U);
}
inline ::uint64_t CasterNode::pub_tcp_delay() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.pub_tcp_delay)
  return _internal_pub_tcp_delay();
}
inline void CasterNode::set_pub_tcp_delay(::uint64_t value) {
  _internal_set_pub_tcp_delay(value);
  SetHasBit(_impl_._has_bits_[0], 0x00002000U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.pub_tcp_delay)
}
inline ::uint64_t CasterNode::_internal_pub_tcp_delay() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pub_tcp_delay_;
}
inline void CasterNode::_internal_set_pub_tcp_delay(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pub_tcp_delay_ = value;
}

// string run_platform = 14;
inline void CasterNode::clear_run_platform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.run_platform_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::std::string& CasterNode::run_platform() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.run_platform)
  return _internal_run_platform();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CasterNode::set_run_platform(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.run_platform_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.run_platform)
}
inline ::std::string* PROTOBUF_NONNULL CasterNode::mutable_run_platform()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::std::string* _s = _internal_mutable_run_platform();
  // @@protoc_insertion_point(field_mutable:caster.service.CasterNode.run_platform)
  return _s;
}
inline const ::std::string& CasterNode::_internal_run_platform() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.run_platform_.Get();
}
inline void CasterNode::_internal_set_run_platform(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.run_platform_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CasterNode::_internal_mutable_run_platform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.run_platform_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CasterNode::release_run_platform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.service.CasterNode.run_platform)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000010U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  auto* released = _impl_.run_platform_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.run_platform_.Set("", GetArena());
  }
  return released;
}
inline void CasterNode::set_allocated_run_platform(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  _impl_.run_platform_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.run_platform_.IsDefault()) {
    _impl_.run_platform_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.service.CasterNode.run_platform)
}

// uint64 send_total = 15;
inline void CasterNode::clear_send_total() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.send_total_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00004000U);
}
inline ::uint64_t CasterNode::send_total() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.send_total)
  return _internal_send_total();
}
inline void CasterNode::set_send_total(::uint64_t value) {
  _internal_set_send_total(value);
  SetHasBit(_impl_._has_bits_[0], 0x00004000U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.send_total)
}
inline ::uint64_t CasterNode::_internal_send_total() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.send_total_;
}
inline void CasterNode::_internal_set_send_total(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.send_total_ = value;
}

// double send_speed = 16;
inline void CasterNode::clear_send_speed() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.send_speed_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00008000U);
}
inline double CasterNode::send_speed() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.send_speed)
  return _internal_send_speed();
}
inline void CasterNode::set_send_speed(double value) {
  _internal_set_send_speed(value);
  SetHasBit(_impl_._has_bits_[0], 0x00008000U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.send_speed)
}
inline double CasterNode::_internal_send_speed() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.send_speed_;
}
inline void CasterNode::_internal_set_send_speed(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.send_speed_ = value;
}

// uint64 recv_total = 17;
inline void CasterNode::clear_recv_total() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.recv_total_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00010000U);
}
inline ::uint64_t CasterNode::recv_total() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.recv_total)
  return _internal_recv_total();
}
inline void CasterNode::set_recv_total(::uint64_t value) {
  _internal_set_recv_total(value);
  SetHasBit(_impl_._has_bits_[0], 0x00010000U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.recv_total)
}
inline ::uint64_t CasterNode::_internal_recv_total() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.recv_total_;
}
inline void CasterNode::_internal_set_recv_total(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.recv_total_ = value;
}

// double recv_speed = 18;
inline void CasterNode::clear_recv_speed() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.recv_speed_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00020000U);
}
inline double CasterNode::recv_speed() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.recv_speed)
  return _internal_recv_speed();
}
inline void CasterNode::set_recv_speed(double value) {
  _internal_set_recv_speed(value);
  SetHasBit(_impl_._has_bits_[0], 0x00020000U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.recv_speed)
}
inline double CasterNode::_internal_recv_speed() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.recv_speed_;
}
inline void CasterNode::_internal_set_recv_speed(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.recv_speed_ = value;
}

// uint32 connect_count = 19;
inline void CasterNode::clear_connect_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.connect_count_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00040000U);
}
inline ::uint32_t CasterNode::connect_count() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.connect_count)
  return _internal_connect_count();
}
inline void CasterNode::set_connect_count(::uint32_t value) {
  _internal_set_connect_count(value);
  SetHasBit(_impl_._has_bits_[0], 0x00040000U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.connect_count)
}
inline ::uint32_t CasterNode::_internal_connect_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.connect_count_;
}
inline void CasterNode::_internal_set_connect_count(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.connect_count_ = value;
}

// uint32 server_count = 20;
inline void CasterNode::clear_server_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_count_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00080000U);
}
inline ::uint32_t CasterNode::server_count() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.server_count)
  return _internal_server_count();
}
inline void CasterNode::set_server_count(::uint32_t value) {
  _internal_set_server_count(value);
  SetHasBit(_impl_._has_bits_[0], 0x00080000U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.server_count)
}
inline ::uint32_t CasterNode::_internal_server_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.server_count_;
}
inline void CasterNode::_internal_set_server_count(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_count_ = value;
}

// uint32 client_count = 21;
inline void CasterNode::clear_client_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.client_count_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00100000U);
}
inline ::uint32_t CasterNode::client_count() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.client_count)
  return _internal_client_count();
}
inline void CasterNode::set_client_count(::uint32_t value) {
  _internal_set_client_count(value);
  SetHasBit(_impl_._has_bits_[0], 0x00100000U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.client_count)
}
inline ::uint32_t CasterNode::_internal_client_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.client_count_;
}
inline void CasterNode::_internal_set_client_count(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.client_count_ = value;
}

// uint32 pull_count = 22;
inline void CasterNode::clear_pull_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pull_count_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00200000U);
}
inline ::uint32_t CasterNode::pull_count() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.pull_count)
  return _internal_pull_count();
}
inline void CasterNode::set_pull_count(::uint32_t value) {
  _internal_set_pull_count(value);
  SetHasBit(_impl_._has_bits_[0], 0x00200000U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.pull_count)
}
inline ::uint32_t CasterNode::_internal_pull_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pull_count_;
}
inline void CasterNode::_internal_set_pull_count(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pull_count_ = value;
}

// uint32 push_count = 23;
inline void CasterNode::clear_push_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.push_count_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00400000U);
}
inline ::uint32_t CasterNode::push_count() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.push_count)
  return _internal_push_count();
}
inline void CasterNode::set_push_count(::uint32_t value) {
  _internal_set_push_count(value);
  SetHasBit(_impl_._has_bits_[0], 0x00400000U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.push_count)
}
inline ::uint32_t CasterNode::_internal_push_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.push_count_;
}
inline void CasterNode::_internal_set_push_count(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.push_count_ = value;
}

// uint32 proxy_count = 24;
inline void CasterNode::clear_proxy_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.proxy_count_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00800000U);
}
inline ::uint32_t CasterNode::proxy_count() const {
  // @@protoc_insertion_point(field_get:caster.service.CasterNode.proxy_count)
  return _internal_proxy_count();
}
inline void CasterNode::set_proxy_count(::uint32_t value) {
  _internal_set_proxy_count(value);
  SetHasBit(_impl_._has_bits_[0], 0x00800000U);
  // @@protoc_insertion_point(field_set:caster.service.CasterNode.proxy_count)
}
inline ::uint32_t CasterNode::_internal_proxy_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.proxy_count_;
}
inline void CasterNode::_internal_set_proxy_count(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.proxy_count_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace service
}  // namespace caster


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // service_2fCasterNode_2eproto_2epb_2eh
