// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/opt_auth_verify.proto
// Protobuf C++ Version: 7.35.0-dev

#include "service/opt_auth_verify.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::caster::service::AuthVerifyOpt
        {&::_pbi::kDescriptorMethods, &::descriptor_table_service_2fopt_5fauth_5fverify_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace caster {
namespace service {

inline constexpr AuthVerifyOpt::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        redis_host_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        redis_password_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        redis_port_{0},
        base_anonymous_login_{false},
        base_online_protection_{false},
        rover_anonymous_login_{false},
        rover_online_protection_{false},
        source_anonymous_login_{false} {}

template <typename>
constexpr AuthVerifyOpt::AuthVerifyOpt(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(AuthVerifyOpt_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct AuthVerifyOptGlobalsTypeInternal {
  constexpr AuthVerifyOptGlobalsTypeInternal() : _default(::_pbi::ConstantInitialized{}) {}
  ~AuthVerifyOptGlobalsTypeInternal() {}
  union {
    AuthVerifyOpt _default;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthVerifyOptGlobalsTypeInternal _AuthVerifyOpt_globals_;
}  // namespace service
}  // namespace caster
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_service_2fopt_5fauth_5fverify_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_service_2fopt_5fauth_5fverify_2eproto = nullptr;
const ::uint32_t
    TableStruct_service_2fopt_5fauth_5fverify_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::caster::service::AuthVerifyOpt, _impl_._has_bits_),
        11, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::caster::service::AuthVerifyOpt, _impl_.redis_host_),
        PROTOBUF_FIELD_OFFSET(::caster::service::AuthVerifyOpt, _impl_.redis_port_),
        PROTOBUF_FIELD_OFFSET(::caster::service::AuthVerifyOpt, _impl_.redis_password_),
        PROTOBUF_FIELD_OFFSET(::caster::service::AuthVerifyOpt, _impl_.base_anonymous_login_),
        PROTOBUF_FIELD_OFFSET(::caster::service::AuthVerifyOpt, _impl_.base_online_protection_),
        PROTOBUF_FIELD_OFFSET(::caster::service::AuthVerifyOpt, _impl_.rover_anonymous_login_),
        PROTOBUF_FIELD_OFFSET(::caster::service::AuthVerifyOpt, _impl_.rover_online_protection_),
        PROTOBUF_FIELD_OFFSET(::caster::service::AuthVerifyOpt, _impl_.source_anonymous_login_),
        0,
        2,
        1,
        3,
        4,
        5,
        6,
        7,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::caster::service::AuthVerifyOpt)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::caster::service::_AuthVerifyOpt_globals_._default,
};
const char descriptor_table_protodef_service_2fopt_5fauth_5fverify_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\035service/opt_auth_verify.proto\022\016caster."
    "service\"\355\001\n\rAuthVerifyOpt\022\022\n\nredis_host\030"
    "\001 \001(\t\022\022\n\nredis_port\030\002 \001(\005\022\026\n\016redis_passw"
    "ord\030\003 \001(\t\022\034\n\024base_anonymous_login\030\004 \001(\010\022"
    "\036\n\026base_online_protection\030\005 \001(\010\022\035\n\025rover"
    "_anonymous_login\030\006 \001(\010\022\037\n\027rover_online_p"
    "rotection\030\007 \001(\010\022\036\n\026source_anonymous_logi"
    "n\030\010 \001(\010b\006proto3"
};
static ::absl::once_flag descriptor_table_service_2fopt_5fauth_5fverify_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_service_2fopt_5fauth_5fverify_2eproto = {
    false,
    false,
    295,
    descriptor_table_protodef_service_2fopt_5fauth_5fverify_2eproto,
    "service/opt_auth_verify.proto",
    &descriptor_table_service_2fopt_5fauth_5fverify_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_service_2fopt_5fauth_5fverify_2eproto::offsets,
    file_level_enum_descriptors_service_2fopt_5fauth_5fverify_2eproto,
    file_level_service_descriptors_service_2fopt_5fauth_5fverify_2eproto,
};
namespace caster {
namespace service {
// ===================================================================

class AuthVerifyOpt::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<AuthVerifyOpt>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_._has_bits_);
};

AuthVerifyOpt::AuthVerifyOpt(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AuthVerifyOpt_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:caster.service.AuthVerifyOpt)
}
PROTOBUF_NDEBUG_INLINE AuthVerifyOpt::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::caster::service::AuthVerifyOpt& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        redis_host_(arena, from.redis_host_),
        redis_password_(arena, from.redis_password_) {}

AuthVerifyOpt::AuthVerifyOpt(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const AuthVerifyOpt& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AuthVerifyOpt_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AuthVerifyOpt* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, redis_port_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, redis_port_),
           offsetof(Impl_, source_anonymous_login_) -
               offsetof(Impl_, redis_port_) +
               sizeof(Impl_::source_anonymous_login_));

  // @@protoc_insertion_point(copy_constructor:caster.service.AuthVerifyOpt)
}
PROTOBUF_NDEBUG_INLINE AuthVerifyOpt::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        redis_host_(arena),
        redis_password_(arena) {}

inline void AuthVerifyOpt::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, redis_port_),
           0,
           offsetof(Impl_, source_anonymous_login_) -
               offsetof(Impl_, redis_port_) +
               sizeof(Impl_::source_anonymous_login_));
}
AuthVerifyOpt::~AuthVerifyOpt() {
  // @@protoc_insertion_point(destructor:caster.service.AuthVerifyOpt)
  SharedDtor(*this);
}
inline void AuthVerifyOpt::SharedDtor(MessageLite& self) {
  AuthVerifyOpt& this_ = static_cast<AuthVerifyOpt&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.redis_host_.Destroy();
  this_._impl_.redis_password_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL AuthVerifyOpt::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AuthVerifyOpt(arena);
}
constexpr auto AuthVerifyOpt::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AuthVerifyOpt),
                                            alignof(AuthVerifyOpt));
}
constexpr auto AuthVerifyOpt::InternalGenerateClassData_() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_AuthVerifyOpt_globals_._default,
          &_table_.header,
          nullptr,  // IsInitialized
          &AuthVerifyOpt::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<AuthVerifyOpt>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AuthVerifyOpt::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<AuthVerifyOpt>(), &AuthVerifyOpt::ByteSizeLong,
              &AuthVerifyOpt::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_._cached_size_),
          false,
      },
      &file_reflection_data[0]};
#else  // !PROTOBUF_MESSAGE_GLOBALS
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_AuthVerifyOpt_globals_._default,
          &_table_.header,
          nullptr,  // IsInitialized
          &AuthVerifyOpt::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<AuthVerifyOpt>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AuthVerifyOpt::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<AuthVerifyOpt>(), &AuthVerifyOpt::ByteSizeLong,
              &AuthVerifyOpt::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_._cached_size_),
          false,
      },
      &::_pbi::kDescriptorMethods,
      &descriptor_table_service_2fopt_5fauth_5fverify_2eproto,
      nullptr,  // tracker
  };
#endif  // PROTOBUF_MESSAGE_GLOBALS
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull AuthVerifyOpt_class_data_ =
        AuthVerifyOpt::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AuthVerifyOpt::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&AuthVerifyOpt_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(AuthVerifyOpt_class_data_.tc_table);
  return AuthVerifyOpt_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 0, 69, 2>
AuthVerifyOpt::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    AuthVerifyOpt_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::caster::service::AuthVerifyOpt>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool source_anonymous_login = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(AuthVerifyOpt, _impl_.source_anonymous_login_), 7>(),
     {64, 7, 0,
      PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_.source_anonymous_login_)}},
    // string redis_host = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_.redis_host_)}},
    // int32 redis_port = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AuthVerifyOpt, _impl_.redis_port_), 2>(),
     {16, 2, 0,
      PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_.redis_port_)}},
    // string redis_password = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_.redis_password_)}},
    // bool base_anonymous_login = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(AuthVerifyOpt, _impl_.base_anonymous_login_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_.base_anonymous_login_)}},
    // bool base_online_protection = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(AuthVerifyOpt, _impl_.base_online_protection_), 4>(),
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_.base_online_protection_)}},
    // bool rover_anonymous_login = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(AuthVerifyOpt, _impl_.rover_anonymous_login_), 5>(),
     {48, 5, 0,
      PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_.rover_anonymous_login_)}},
    // bool rover_online_protection = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(AuthVerifyOpt, _impl_.rover_online_protection_), 6>(),
     {56, 6, 0,
      PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_.rover_online_protection_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string redis_host = 1;
    {PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_.redis_host_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 redis_port = 2;
    {PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_.redis_port_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string redis_password = 3;
    {PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_.redis_password_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool base_anonymous_login = 4;
    {PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_.base_anonymous_login_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // bool base_online_protection = 5;
    {PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_.base_online_protection_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // bool rover_anonymous_login = 6;
    {PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_.rover_anonymous_login_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // bool rover_online_protection = 7;
    {PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_.rover_online_protection_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // bool source_anonymous_login = 8;
    {PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_.source_anonymous_login_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\34\12\0\16\0\0\0\0\0\0\0\0\0\0\0\0"
    "caster.service.AuthVerifyOpt"
    "redis_host"
    "redis_password"
  }},
};
PROTOBUF_NOINLINE void AuthVerifyOpt::Clear() {
// @@protoc_insertion_point(message_clear_start:caster.service.AuthVerifyOpt)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.redis_host_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.redis_password_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000fcU)) {
    ::memset(&_impl_.redis_port_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.source_anonymous_login_) -
        reinterpret_cast<char*>(&_impl_.redis_port_)) + sizeof(_impl_.source_anonymous_login_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AuthVerifyOpt::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AuthVerifyOpt& this_ = static_cast<const AuthVerifyOpt&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AuthVerifyOpt::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AuthVerifyOpt& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:caster.service.AuthVerifyOpt)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string redis_host = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_redis_host().empty()) {
      const ::std::string& _s = this_._internal_redis_host();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "caster.service.AuthVerifyOpt.redis_host");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // int32 redis_port = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_redis_port() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_redis_port(), target);
    }
  }

  // string redis_password = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_redis_password().empty()) {
      const ::std::string& _s = this_._internal_redis_password();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "caster.service.AuthVerifyOpt.redis_password");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // bool base_anonymous_login = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_base_anonymous_login() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          4, this_._internal_base_anonymous_login(), target);
    }
  }

  // bool base_online_protection = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_base_online_protection() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          5, this_._internal_base_online_protection(), target);
    }
  }

  // bool rover_anonymous_login = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_rover_anonymous_login() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          6, this_._internal_rover_anonymous_login(), target);
    }
  }

  // bool rover_online_protection = 7;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_rover_online_protection() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          7, this_._internal_rover_online_protection(), target);
    }
  }

  // bool source_anonymous_login = 8;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_source_anonymous_login() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          8, this_._internal_source_anonymous_login(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:caster.service.AuthVerifyOpt)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AuthVerifyOpt::ByteSizeLong(const MessageLite& base) {
  const AuthVerifyOpt& this_ = static_cast<const AuthVerifyOpt&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AuthVerifyOpt::ByteSizeLong() const {
  const AuthVerifyOpt& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:caster.service.AuthVerifyOpt)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // string redis_host = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_redis_host().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_redis_host());
      }
    }
    // string redis_password = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_redis_password().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_redis_password());
      }
    }
    // int32 redis_port = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_redis_port() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_redis_port());
      }
    }
    // bool base_anonymous_login = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_base_anonymous_login() != 0) {
        total_size += 2;
      }
    }
    // bool base_online_protection = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_base_online_protection() != 0) {
        total_size += 2;
      }
    }
    // bool rover_anonymous_login = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_rover_anonymous_login() != 0) {
        total_size += 2;
      }
    }
    // bool rover_online_protection = 7;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_rover_online_protection() != 0) {
        total_size += 2;
      }
    }
    // bool source_anonymous_login = 8;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_source_anonymous_login() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void AuthVerifyOpt::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<AuthVerifyOpt*>(&to_msg);
  auto& from = static_cast<const AuthVerifyOpt&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:caster.service.AuthVerifyOpt)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_redis_host().empty()) {
        _this->_internal_set_redis_host(from._internal_redis_host());
      } else {
        if (_this->_impl_.redis_host_.IsDefault()) {
          _this->_internal_set_redis_host("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_redis_password().empty()) {
        _this->_internal_set_redis_password(from._internal_redis_password());
      } else {
        if (_this->_impl_.redis_password_.IsDefault()) {
          _this->_internal_set_redis_password("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_redis_port() != 0) {
        _this->_impl_.redis_port_ = from._impl_.redis_port_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_base_anonymous_login() != 0) {
        _this->_impl_.base_anonymous_login_ = from._impl_.base_anonymous_login_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_base_online_protection() != 0) {
        _this->_impl_.base_online_protection_ = from._impl_.base_online_protection_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_rover_anonymous_login() != 0) {
        _this->_impl_.rover_anonymous_login_ = from._impl_.rover_anonymous_login_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_rover_online_protection() != 0) {
        _this->_impl_.rover_online_protection_ = from._impl_.rover_online_protection_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_source_anonymous_login() != 0) {
        _this->_impl_.source_anonymous_login_ = from._impl_.source_anonymous_login_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void AuthVerifyOpt::CopyFrom(const AuthVerifyOpt& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:caster.service.AuthVerifyOpt)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AuthVerifyOpt::InternalSwap(AuthVerifyOpt* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.redis_host_, &other->_impl_.redis_host_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.redis_password_, &other->_impl_.redis_password_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_.source_anonymous_login_)
      + sizeof(AuthVerifyOpt::_impl_.source_anonymous_login_)
      - PROTOBUF_FIELD_OFFSET(AuthVerifyOpt, _impl_.redis_port_)>(
          reinterpret_cast<char*>(&_impl_.redis_port_),
          reinterpret_cast<char*>(&other->_impl_.redis_port_));
}

::google::protobuf::Metadata AuthVerifyOpt::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace service
}  // namespace caster
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_service_2fopt_5fauth_5fverify_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
