// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service/opt_auth_verify.proto
// Protobuf C++ Version: 7.35.0-dev

#ifndef service_2fopt_5fauth_5fverify_2eproto_2epb_2eh
#define service_2fopt_5fauth_5fverify_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_service_2fopt_5fauth_5fverify_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_service_2fopt_5fauth_5fverify_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_service_2fopt_5fauth_5fverify_2eproto;
}  // extern "C"
namespace caster {
namespace service {
class AuthVerifyOpt;
struct AuthVerifyOptGlobalsTypeInternal;
extern AuthVerifyOptGlobalsTypeInternal _AuthVerifyOpt_globals_;
extern const ::google::protobuf::internal::ClassDataFull AuthVerifyOpt_class_data_;
}  // namespace service
}  // namespace caster
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace caster {
namespace service {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED AuthVerifyOpt final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:caster.service.AuthVerifyOpt) */ {
 public:
  inline AuthVerifyOpt() : AuthVerifyOpt(nullptr) {}
  ~AuthVerifyOpt() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AuthVerifyOpt* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AuthVerifyOpt));
  }
#endif

  template <typename = void>
  explicit constexpr AuthVerifyOpt(::google::protobuf::internal::ConstantInitialized);

  inline AuthVerifyOpt(const AuthVerifyOpt& from) : AuthVerifyOpt(nullptr, from) {}
  inline AuthVerifyOpt(AuthVerifyOpt&& from) noexcept
      : AuthVerifyOpt(nullptr, ::std::move(from)) {}
  inline AuthVerifyOpt& operator=(const AuthVerifyOpt& from) {
    CopyFrom(from);
    return *this;
  }
  inline AuthVerifyOpt& operator=(AuthVerifyOpt&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const AuthVerifyOpt& default_instance() {
    return *reinterpret_cast<const AuthVerifyOpt*>(&_AuthVerifyOpt_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AuthVerifyOpt& a, AuthVerifyOpt& b) { a.Swap(&b); }
  inline void Swap(AuthVerifyOpt* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AuthVerifyOpt* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] AuthVerifyOpt* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AuthVerifyOpt>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AuthVerifyOpt& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AuthVerifyOpt& from) { AuthVerifyOpt::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AuthVerifyOpt* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "caster.service.AuthVerifyOpt"; }

  explicit AuthVerifyOpt(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AuthVerifyOpt(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AuthVerifyOpt& from);
  AuthVerifyOpt(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AuthVerifyOpt&& from) noexcept
      : AuthVerifyOpt(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRedisHostFieldNumber = 1,
    kRedisPasswordFieldNumber = 3,
    kRedisPortFieldNumber = 2,
    kBaseAnonymousLoginFieldNumber = 4,
    kBaseOnlineProtectionFieldNumber = 5,
    kRoverAnonymousLoginFieldNumber = 6,
    kRoverOnlineProtectionFieldNumber = 7,
    kSourceAnonymousLoginFieldNumber = 8,
  };
  // string redis_host = 1;
  void clear_redis_host() ;
  [[nodiscard]] const ::std::string& redis_host() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_redis_host(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_redis_host();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_redis_host();
  void set_allocated_redis_host(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_redis_host() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_redis_host(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_redis_host();

  public:
  // string redis_password = 3;
  void clear_redis_password() ;
  [[nodiscard]] const ::std::string& redis_password() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_redis_password(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_redis_password();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_redis_password();
  void set_allocated_redis_password(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_redis_password() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_redis_password(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_redis_password();

  public:
  // int32 redis_port = 2;
  void clear_redis_port() ;
  [[nodiscard]] ::int32_t redis_port() const;
  void set_redis_port(::int32_t value);

  private:
  ::int32_t _internal_redis_port() const;
  void _internal_set_redis_port(::int32_t value);

  public:
  // bool base_anonymous_login = 4;
  void clear_base_anonymous_login() ;
  [[nodiscard]] bool base_anonymous_login() const;
  void set_base_anonymous_login(bool value);

  private:
  bool _internal_base_anonymous_login() const;
  void _internal_set_base_anonymous_login(bool value);

  public:
  // bool base_online_protection = 5;
  void clear_base_online_protection() ;
  [[nodiscard]] bool base_online_protection() const;
  void set_base_online_protection(bool value);

  private:
  bool _internal_base_online_protection() const;
  void _internal_set_base_online_protection(bool value);

  public:
  // bool rover_anonymous_login = 6;
  void clear_rover_anonymous_login() ;
  [[nodiscard]] bool rover_anonymous_login() const;
  void set_rover_anonymous_login(bool value);

  private:
  bool _internal_rover_anonymous_login() const;
  void _internal_set_rover_anonymous_login(bool value);

  public:
  // bool rover_online_protection = 7;
  void clear_rover_online_protection() ;
  [[nodiscard]] bool rover_online_protection() const;
  void set_rover_online_protection(bool value);

  private:
  bool _internal_rover_online_protection() const;
  void _internal_set_rover_online_protection(bool value);

  public:
  // bool source_anonymous_login = 8;
  void clear_source_anonymous_login() ;
  [[nodiscard]] bool source_anonymous_login() const;
  void set_source_anonymous_login(bool value);

  private:
  bool _internal_source_anonymous_login() const;
  void _internal_set_source_anonymous_login(bool value);

  public:
  // @@protoc_insertion_point(class_scope:caster.service.AuthVerifyOpt)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8,
                                   0, 69,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AuthVerifyOpt& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr redis_host_;
    ::google::protobuf::internal::ArenaStringPtr redis_password_;
    ::int32_t redis_port_;
    bool base_anonymous_login_;
    bool base_online_protection_;
    bool rover_anonymous_login_;
    bool rover_online_protection_;
    bool source_anonymous_login_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_service_2fopt_5fauth_5fverify_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AuthVerifyOpt_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AuthVerifyOpt

// string redis_host = 1;
inline void AuthVerifyOpt::clear_redis_host() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.redis_host_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& AuthVerifyOpt::redis_host() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.service.AuthVerifyOpt.redis_host)
  return _internal_redis_host();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void AuthVerifyOpt::set_redis_host(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.redis_host_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.service.AuthVerifyOpt.redis_host)
}
inline ::std::string* PROTOBUF_NONNULL AuthVerifyOpt::mutable_redis_host()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_redis_host();
  // @@protoc_insertion_point(field_mutable:caster.service.AuthVerifyOpt.redis_host)
  return _s;
}
inline const ::std::string& AuthVerifyOpt::_internal_redis_host() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.redis_host_.Get();
}
inline void AuthVerifyOpt::_internal_set_redis_host(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.redis_host_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL AuthVerifyOpt::_internal_mutable_redis_host() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.redis_host_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE AuthVerifyOpt::release_redis_host() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.service.AuthVerifyOpt.redis_host)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.redis_host_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.redis_host_.Set("", GetArena());
  }
  return released;
}
inline void AuthVerifyOpt::set_allocated_redis_host(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.redis_host_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.redis_host_.IsDefault()) {
    _impl_.redis_host_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.service.AuthVerifyOpt.redis_host)
}

// int32 redis_port = 2;
inline void AuthVerifyOpt::clear_redis_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.redis_port_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t AuthVerifyOpt::redis_port() const {
  // @@protoc_insertion_point(field_get:caster.service.AuthVerifyOpt.redis_port)
  return _internal_redis_port();
}
inline void AuthVerifyOpt::set_redis_port(::int32_t value) {
  _internal_set_redis_port(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:caster.service.AuthVerifyOpt.redis_port)
}
inline ::int32_t AuthVerifyOpt::_internal_redis_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.redis_port_;
}
inline void AuthVerifyOpt::_internal_set_redis_port(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.redis_port_ = value;
}

// string redis_password = 3;
inline void AuthVerifyOpt::clear_redis_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.redis_password_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& AuthVerifyOpt::redis_password() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:caster.service.AuthVerifyOpt.redis_password)
  return _internal_redis_password();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void AuthVerifyOpt::set_redis_password(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.redis_password_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:caster.service.AuthVerifyOpt.redis_password)
}
inline ::std::string* PROTOBUF_NONNULL AuthVerifyOpt::mutable_redis_password()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_redis_password();
  // @@protoc_insertion_point(field_mutable:caster.service.AuthVerifyOpt.redis_password)
  return _s;
}
inline const ::std::string& AuthVerifyOpt::_internal_redis_password() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.redis_password_.Get();
}
inline void AuthVerifyOpt::_internal_set_redis_password(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.redis_password_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL AuthVerifyOpt::_internal_mutable_redis_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.redis_password_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE AuthVerifyOpt::release_redis_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:caster.service.AuthVerifyOpt.redis_password)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.redis_password_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.redis_password_.Set("", GetArena());
  }
  return released;
}
inline void AuthVerifyOpt::set_allocated_redis_password(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.redis_password_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.redis_password_.IsDefault()) {
    _impl_.redis_password_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:caster.service.AuthVerifyOpt.redis_password)
}

// bool base_anonymous_login = 4;
inline void AuthVerifyOpt::clear_base_anonymous_login() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.base_anonymous_login_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline bool AuthVerifyOpt::base_anonymous_login() const {
  // @@protoc_insertion_point(field_get:caster.service.AuthVerifyOpt.base_anonymous_login)
  return _internal_base_anonymous_login();
}
inline void AuthVerifyOpt::set_base_anonymous_login(bool value) {
  _internal_set_base_anonymous_login(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:caster.service.AuthVerifyOpt.base_anonymous_login)
}
inline bool AuthVerifyOpt::_internal_base_anonymous_login() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.base_anonymous_login_;
}
inline void AuthVerifyOpt::_internal_set_base_anonymous_login(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.base_anonymous_login_ = value;
}

// bool base_online_protection = 5;
inline void AuthVerifyOpt::clear_base_online_protection() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.base_online_protection_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline bool AuthVerifyOpt::base_online_protection() const {
  // @@protoc_insertion_point(field_get:caster.service.AuthVerifyOpt.base_online_protection)
  return _internal_base_online_protection();
}
inline void AuthVerifyOpt::set_base_online_protection(bool value) {
  _internal_set_base_online_protection(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:caster.service.AuthVerifyOpt.base_online_protection)
}
inline bool AuthVerifyOpt::_internal_base_online_protection() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.base_online_protection_;
}
inline void AuthVerifyOpt::_internal_set_base_online_protection(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.base_online_protection_ = value;
}

// bool rover_anonymous_login = 6;
inline void AuthVerifyOpt::clear_rover_anonymous_login() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rover_anonymous_login_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline bool AuthVerifyOpt::rover_anonymous_login() const {
  // @@protoc_insertion_point(field_get:caster.service.AuthVerifyOpt.rover_anonymous_login)
  return _internal_rover_anonymous_login();
}
inline void AuthVerifyOpt::set_rover_anonymous_login(bool value) {
  _internal_set_rover_anonymous_login(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:caster.service.AuthVerifyOpt.rover_anonymous_login)
}
inline bool AuthVerifyOpt::_internal_rover_anonymous_login() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rover_anonymous_login_;
}
inline void AuthVerifyOpt::_internal_set_rover_anonymous_login(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rover_anonymous_login_ = value;
}

// bool rover_online_protection = 7;
inline void AuthVerifyOpt::clear_rover_online_protection() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rover_online_protection_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline bool AuthVerifyOpt::rover_online_protection() const {
  // @@protoc_insertion_point(field_get:caster.service.AuthVerifyOpt.rover_online_protection)
  return _internal_rover_online_protection();
}
inline void AuthVerifyOpt::set_rover_online_protection(bool value) {
  _internal_set_rover_online_protection(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:caster.service.AuthVerifyOpt.rover_online_protection)
}
inline bool AuthVerifyOpt::_internal_rover_online_protection() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rover_online_protection_;
}
inline void AuthVerifyOpt::_internal_set_rover_online_protection(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rover_online_protection_ = value;
}

// bool source_anonymous_login = 8;
inline void AuthVerifyOpt::clear_source_anonymous_login() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_anonymous_login_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline bool AuthVerifyOpt::source_anonymous_login() const {
  // @@protoc_insertion_point(field_get:caster.service.AuthVerifyOpt.source_anonymous_login)
  return _internal_source_anonymous_login();
}
inline void AuthVerifyOpt::set_source_anonymous_login(bool value) {
  _internal_set_source_anonymous_login(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:caster.service.AuthVerifyOpt.source_anonymous_login)
}
inline bool AuthVerifyOpt::_internal_source_anonymous_login() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.source_anonymous_login_;
}
inline void AuthVerifyOpt::_internal_set_source_anonymous_login(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_anonymous_login_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace service
}  // namespace caster


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // service_2fopt_5fauth_5fverify_2eproto_2epb_2eh
