syntax = "proto3";
package caster.core;

// 监听器的配置  改为protobuf形式是为了能够远程下发配置
// 接入配置

enum BroadcastType
{
  BOARDCAST_TYPE_UNSPECIFIED    = 0; // 未指定的广播类型
  BOARDCAST_TYPE_SERVER_OPERATE = 1; // 服务器操作相关的广播
  BOARDCAST_TYPE_CLIENT_OPERATE = 2; // 客户端操作相关的广播
  BOARDCAST_TYPE_RUSH_OPERATE   = 3;
  BOARDCAST_TYPE_PULL_OPERATE   = 4;
}

enum BroadcastOperateType
{
  BOARDCAST_OPERATE_UNSPECIFIED = 0; // 未指定的操作类型
  BOARDCAST_OPERATE_CREATE      = 1; // 添加
  BOARDCAST_OPERATE_UPDATE      = 2; // 更新
  BOARDCAST_OPERATE_DELETE      = 3; // 删除
  BOARDCAST_OPERATR_ACTIVE      = 4; // 激活
  BOARDCAST_OPERATR_INACTIVE    = 5; // 取消激活
}

message BroadcastMsg {
  BroadcastType        type       = 1; // 广播类型
  BroadcastOperateType operate    = 2; // 操作类型
  string               target     = 3; // 相关对象的唯一标识，例如节点ID、连接ID等
  string               msg_str    = 4 ; // 请求字符串，包含了请求的具体内容，可以
  string               reason_str = 5; // 原因
}
