syntax = "proto3";
package caster.core;

// 基站连接状态

message ServerState {
  string uid            = 1; // connect_key
  uint64 online_time    = 2; // 上线时刻
  uint64 update_time    = 3; // 更新时刻

  string login_mpt      = 4; // 接入的挂载点
  string alias_mpt      = 5; // 对外服务的名称
  int32  type           = 6; // 挂载点类型
  string account        = 7; // 账户名
  string ip             = 8; // 连接IP
  int32  port           = 9; // 连接端口
  uint64 online_seconds = 10; // 在线时长(秒)    // 通过上线时刻和当前时刻计算得到的在线时长，单位为秒
  uint64 tcp_delay      = 11; // TCP延迟(微秒)

  double ecef_x               = 12;
  double ecef_y               = 13;
  double ecef_z               = 14;
  int64  position_update_time = 15;
}