// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Common.proto
// Protobuf C++ Version: 7.35.0-dev

#include "Common.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace caster {
}  // namespace caster
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_Common_2eproto[5];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_Common_2eproto = nullptr;
const ::uint32_t TableStruct_Common_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* PROTOBUF_NULLABLE schemas = nullptr;
static constexpr ::_pb::Message* PROTOBUF_NONNULL const* PROTOBUF_NULLABLE
    file_default_instances = nullptr;
const char descriptor_table_protodef_Common_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014Common.proto\022\006caster*\207\001\n\010PullType\022\025\n\021P"
    "ULL_TYPE_UNKNOWN\020\000\022\027\n\023PULL_TYPE_NTRIP_1_"
    "0\020\001\022\027\n\023PULL_TYPE_NTRIP_2_0\020\002\022\030\n\024PULL_TYP"
    "E_TCP_CLIENT\020\003\022\030\n\024PULL_TYPE_TCP_SERVER\020\004"
    "*\207\001\n\010PushType\022\025\n\021PUSH_TYPE_UNKNOWN\020\000\022\027\n\023"
    "PUSH_TYPE_NTRIP_1_0\020\001\022\027\n\023PUSH_TYPE_NTRIP"
    "_2_0\020\002\022\030\n\024PUSH_TYPE_TCP_CLIENT\020\003\022\030\n\024PUSH"
    "_TYPE_TCP_SERVER\020\004*\310\001\n\020SourceRecordType\022"
    "\036\n\032SOURCE_RECORD_TYPE_UNKNOWN\020\000\022\033\n\027SOURC"
    "E_RECORD_TYPE_REAL\020\001\022\036\n\032SOURCE_RECORD_TY"
    "PE_NEAREST\020\002\022\034\n\030SOURCE_RECORD_TYPE_ALIAS"
    "\020\003\022\034\n\030SOURCE_RECORD_TYPE_PROXY\020\004\022\033\n\027SOUR"
    "CE_RECORD_TYPE_GRID\020\005*n\n\020SourceDecordTyp"
    "e\022\036\n\032SOURCE_DECODE_TYPE_UNKNOWN\020\000\022\033\n\027SOU"
    "RCE_DECODE_TYPE_AUTO\020\001\022\035\n\031SOURCE_DECODE_"
    "TYPE_MANUAL\020\002*\234\001\n\021SourceDisplayType\022\034\n\030S"
    "OURCE_DISP_TYPE_UNKNOWN\020\000\022 \n\034SOURCE_DISP"
    "_TYPE_ALWAYS_SHOW\020\001\022 \n\034SOURCE_DISP_TYPE_"
    "ALWAYS_HIDE\020\002\022%\n!SOURCE_DISP_TYPE_SHOW_W"
    "HEN_ONLINE\020\003b\006proto3"
};
static ::absl::once_flag descriptor_table_Common_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Common_2eproto = {
    false,
    false,
    780,
    descriptor_table_protodef_Common_2eproto,
    "Common.proto",
    &descriptor_table_Common_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_Common_2eproto::offsets,
    file_level_enum_descriptors_Common_2eproto,
    file_level_service_descriptors_Common_2eproto,
};
namespace caster {
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
PullType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Common_2eproto);
  return file_level_enum_descriptors_Common_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t PullType_internal_data_[] = {
    327680u, 0u, };
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
PushType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Common_2eproto);
  return file_level_enum_descriptors_Common_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t PushType_internal_data_[] = {
    327680u, 0u, };
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
SourceRecordType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Common_2eproto);
  return file_level_enum_descriptors_Common_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t SourceRecordType_internal_data_[] = {
    393216u, 0u, };
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
SourceDecordType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Common_2eproto);
  return file_level_enum_descriptors_Common_2eproto[3];
}
PROTOBUF_CONSTINIT const uint32_t SourceDecordType_internal_data_[] = {
    196608u, 0u, };
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
SourceDisplayType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Common_2eproto);
  return file_level_enum_descriptors_Common_2eproto[4];
}
PROTOBUF_CONSTINIT const uint32_t SourceDisplayType_internal_data_[] = {
    262144u, 0u, };
// @@protoc_insertion_point(namespace_scope)
}  // namespace caster
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_Common_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
